module.exports.Soundtracks = {
    flash: {
        season1: 'https://open.spotify.com/album/0xiJwfDcZRQ77bsbjS9TF5',
        season2: 'https://open.spotify.com/album/2EE7W74Rk1LDHzbYC9js2Z',
        season3: 'https://open.spotify.com/album/0DCUAyJVmG1fNxkBaZqFLt',
        season4: 'https://open.spotify.com/album/12WS02J0JBAVeEGj6aJ7R8',
    },
    arrow: {
        season1: 'https://open.spotify.com/album/0Hsit07149488kiRI1UiaJ',
        season2: 'https://open.spotify.com/album/234N1BIHMSxaKSVAM0JrOC',
        season3: 'https://open.spotify.com/album/2SYmYysseasonloAQkkr2TEncT',
        season4: 'https://open.spotify.com/album/1IA3XNL6kv5zOpFG18M1au',
        season5: 'https://open.spotify.com/album/7ivC8XKulyl3akjhiRtJjA',
        season6: 'https://open.spotify.com/album/2sT1ks3i5yn0ZAGGvZQv92',
    },
    supergirl: {
        season1: 'https://open.spotify.com/album/0jSqj8Tr0BrQIdqV4DZ9jD',
        season2: 'https://open.spotify.com/album/7x4PDyJb3FJoYkRnF2hu2K',
        season3: 'https://open.spotify.com/album/6zXns0k78HUh5UlNprKhvf',
    },
    lot: {
        season1: 'https://open.spotify.com/album/0ceTcs3rDUEiyzshxjJFdB',
        season2: 'https://open.spotify.com/album/4r6t4EyqVZskLi0jD9yOhU',
        season3: 'https://open.spotify.com/album/0FPZ6xZBcwsupOaxKULGAF',
    },
    crossovers: {
        crossover1: 'https://open.spotify.com/album/4AtHQFEn8Qrp9aSSt0ehob', //Flash vs. Arrow
        crossover2: 'https://open.spotify.com/album/7vs9fu0ORNPmV2opBjLu5z', //Duet
        crossover3: 'https://open.spotify.com/album/1jFljSQGFqtKkFNURoEOeI', //COEX
    }
};

module.exports.Quotes = {
    sections: [{
        content: [
            {title: 'Category:Alexandra_Danvers_(Arrowverse:_Earth-38)/Quotes'},
            {title: 'Category:Abra_Kadabra_(Arrowverse)/Quotes'},
            {title: 'Category:Francisco_Ramon_(Arrowverse)/Quotes'},
            {title: 'Category:Emiko_Queen_(Arrowverse)/Quotes'},
            {title: 'Category:Floyd_Lawton_(Arrowverse)/Quotes'},
            {title: 'Category:John_Diggle_(Arrowverse)/Quotes' },
            {title: 'Category:Carrie_Cutter_(Arrowverse)/Quotes'},
            {title: 'Category:Jefferson_Jackson_(Arrowverse)/Quotes'},
            {title: 'Category:Ricardo_Diaz_(Arrowverse)/Quotes'},
            {title: 'Category:Maseo_Yamashiro_(Arrowverse)/Quotes'},
            {title: 'Category:Rene_Ramirez_(Arrowverse)/Quotes'},
            {title: 'Category:Benjamin_Turner_(Arrowverse)/Quotes'},
            {title: 'Category:Felicity_Smoak_(Arrowverse)/Quotes'},
            {title: 'Category:Barry_Allen_(Arrowverse)/Quotes'},
            {title: 'Category:Harrison_Wells_(Arrowverse:_Earth-19)/Quotes'},
            {title: 'Category:Evelyn_Sharp_(Arrowverse)/Quotes'},
            {title: 'Category:Amanda_Waller_(Arrowverse)/Quotes'},
            {title: 'Category:Helena_Bertinelli_(Arrowverse)/Quotes'},
            {title: 'Category:Tobias_Church_(Arrowverse)/Quotes'},
            {title: 'Category:Simon_Morrison_(Arrowverse)/Quotes'},
            {title: 'Category:Damien_Darhk_(Arrowverse)/Quotes'},
            {title: 'Category:Roy_Harper_(Arrowverse)/Quotes'},
            {title: 'Category:Samandra_Watson_(Arrowverse)/Quotes'},
            {title: 'Category:Kara_Zor-El_(Arrowverse:_Earth-38)/Quotes'},
            {title: 'Category:Henry_Allen_(Arrowverse)/Quotes'},
            {title: 'Category:Nathaniel_Heywood_(Arrowverse)/Quotes'},
            {title: 'Category:Nora_Thompson_(Arrowverse)/Quotes'},
            {title: 'Category:Catherine_Grant_(Arrowverse:_Earth-38)/Quotes'},
            {title: 'Category:Jesse_Wells_(Arrowverse:_Earth-2)/Quotes'},
            {title: 'Category:George_Lucas_(Arrowverse)/Quotes'},
            {title: 'Category:Mia_Smoak_(Arrowverse)/Quotes'},
            {title: 'Category:Zari_Tomaz_(Arrowverse)/Quotes'},
            {title: 'Category:Winslow_Schott,_Jr._(Arrowverse:_Earth-X)/Quotes'},
            {title: 'Category:Robert_Queen_(Arrowverse)/Quotes'},
            {title: 'Category:Kal-El_(Arrowverse:_Earth-38)/Quotes'},
            {title: 'Category:Leonard_Snart_(Arrowverse)/Quotes'},
            {title: 'Category:Raymond_Palmer_(Arrowverse)/Quotes'},
            {title: 'Category:John_Constantine_(Arrowverse)/Quotes'},
            {title: 'Category:Dinah_Laurel_Lance_(Arrowverse:_Earth-2)/Quotes'},
            {title: 'Category:Martin_Stein_(Arrowverse)/Quotes'},
            {title: 'Category:Barry_Allen_(Arrowverse:_Earth-2)/Quotes'},
            {title: 'Category:Rip_Hunter_(Arrowverse)/Quotes'},
            {title: 'Category:Anatoli_Knyazev_(Arrowverse)/Quotes'},
            {title: 'Category:Mallus_(Arrowverse)/Quotes'},
            {title: 'Category:Hartley_Rathaway_(Arrowverse)/Quotes'},
            {title: 'Category:Leslie_Jocoy_(Arrowverse)/Quotes'},
            {title: 'Category:Harrison_Wells_(Arrowverse:_Earth-2)/Quotes'},
            {title: 'Category:Malcolm_Merlyn_(Arrowverse)/Quotes'},
            {title: 'Category:Nora_West-Allen_(Arrowverse)/Quotes'},
            {title: 'Category:Dinah_Lance_(Arrowverse)/Quotes'},
            {title: 'Category:J%27onn_J%27onzz_(Arrowverse:_Earth-38)/Quotes'},
            {title: 'Category:Leonard_Snart_(Arrowverse:_Earth-X)/Quotes'},
            {title: 'Category:Jay_Garrick_(Arrowverse:_Earth-3)/Quotes'},
            {title: 'Category:Amaya_Jiwe_(Arrowverse)/Quotes'},
            {title: 'Category:John_Diggle,_Jr._(Arrowverse:_Star_City_2046)/Quotes'},
            {title: 'Category:Julian_Albert_Desmond_(Arrowverse)/Quotes'},
            {title: 'Category:Eobard_Thawne_(Arrowverse)/Quotes'},
            {title: 'Category:Hunter_Zolomon_(Arrowverse:_Earth-2)/Quotes'},
            {title: 'Category:Mick_Rory_(Arrowverse)/Quotes'},
            {title: 'Category:James_Olsen_(Arrowverse:_Earth-38)/Quotes'},
            {title: 'Category:Samantha_Clayton_(Arrowverse)/Quotes'},
            {title: 'Category:James_Jesse_(Arrowverse)/Quotes'},
            {title: 'Category:Donna_Smoak_(Arrowverse)/Quotes'},
            {title: 'Category:Music_Meister_(Arrowverse:_Earth-38)/Quotes'},
            {title: 'Category:Nyssa_al_Ghul_(Arrowverse)/Quotes'},
            {title: 'Category:Grodd_(Arrowverse)/Quotes'},
            {title: 'Category:Edward_Clariss_(Arrowverse)/Quotes'},
            {title: 'Category:Ralph_Dibny_(Arrowverse)/Quotes'},
            {title: 'Category:Clyde_Mardon_(Arrowverse)/Quotes'},
            {title: 'Category:Brainiac_8_(Arrowverse:_Earth-38)/Quotes'},
            {title: 'Category:Desmond_(Arrowverse)/Quotes'},
            {title: 'Category:Sara_Lance_(Arrowverse)/Quotes'},
            {title: 'Category:Harleen_Quinzel_(Arrowverse)/Quotes'},
            {title: 'Category:Thomas_Merlyn_(Arrowverse:_Earth-X)/Quotes'},
            {title: 'Category:Katherine_Kane_(Arrowverse)/Quotes'},
            {title: 'Category:Dinah_Laurel_Lance_(Arrowverse)/Quotes'},
            {title: 'Category:Izzy_Bowin_(Arrowverse)/Quotes'},
            {title: 'Category:Edward_Thawne_(Arrowverse)/Quotes'},
            {title: 'Category:Clifford_DeVoe_(Arrowverse)/Quotes'},
            {title: 'Category:John_Deegan_(Arrowverse)/Quotes'},
            {title: 'Category:Iris_West_(Arrowverse)/Quotes'},
            {title: 'Category:Eliza_Danvers_(Arrowverse:_Earth-38)/Quotes'},
            {title: 'Category:Kelex_(Arrowverse:_Earth-38)/Quotes'},
            {title: 'Category:Savitar_(Arrowverse)/Quotes'},
            {title: 'Category:Caitlin_Snow_(Arrowverse)/Quotes'}
        ]}
    ]
};

module.exports.Speedsters = [
    {
        speedster: 'The Flash (Barry Allen)',
        lightningColorsElectrokinesis: 'Yellow (Speed Force) 🡒 Orange (+Speed)',
        universe: 'Earth-1',
        actoractress: 'Grant Gustin',
        firstAppearanceAsSpeedster: 'The Flash 1x01 "Pilot"'
    },
    {
        speedster: 'The Reverse-Flash (Eobard Thawne)',
        lightningColorsElectrokinesis: 'Red (Negative Speed Force)',
        universe: 'Earth-1',
        actoractress: 'Tom Cavanagh / Matt Letscher',
        firstAppearanceAsSpeedster: 'The Flash 1x06 "The Flash Is Born"'
    },
    {
        speedster: 'Zoom / Black Flash (Hunter Zolomon)',
        lightningColorsElectrokinesis: 'Yellow (Speed Force) 🡒 Blue (V6) 🡒 Red (Transformed)',
        universe: 'Earth-2',
        actoractress: 'Teddy Sears / Tony Todd',
        firstAppearanceAsSpeedster: 'The Flash 2x01 "The Man Who Saved Central City" '
    },
    {
        speedster: 'Savitar (Barry Allen - Time Remnant)',
        lightningColorsElectrokinesis: 'Yellow (Speed Force) 🡒 White (Suit)',
        universe: 'Earth-1',
        actoractress: 'Grant Gustin / Tobin Bell',
        firstAppearanceAsSpeedster: 'The Flash 3x02 "Paradox" '
    },
    {
        speedster: 'Godspeed (August Heart)',
        lightningColorsElectrokinesis: 'White (Speed Force) [Tachyons] / Blue Sparks (V9)',
        universe: 'Earth-1',
        actoractress: 'Kindall Charters / B.D. Wong',
        firstAppearanceAsSpeedster: 'The Flash 5x18 "Godspeed"'
    },
    {
        speedster: 'G4 (Unnamed Godspeed)',
        lightningColorsElectrokinesis: 'White (Speed Force) [Clone]',
        universe: 'Earth-1',
        actoractress: 'Ryan Handley',
        firstAppearanceAsSpeedster: 'The Flash 6x01 "Into The Void"'
    },
    {
        speedster: 'Accelerated Man',
        lightningColorsElectrokinesis: 'Purple (Speed Force)',
        universe: 'Earth-19',
        actoractress: 'Sean Poague',
        firstAppearanceAsSpeedster: 'The Flash 3x14 "Attack on Central City"'
    },
    {
        speedster: 'Jesse Quick (Jesse Chambers Wells)',
        lightningColorsElectrokinesis: 'Yellow (Speed Force)',
        universe: 'Earth-2',
        actoractress: 'Violett Beane',
        firstAppearanceAsSpeedster: 'The Flash 3x03 "Magenta" '
    },
    {
        speedster: 'The Flash (Jay Garrick)',
        lightningColorsElectrokinesis: 'Orange (Speed Force)',
        universe: 'Earth-3',
        actoractress: 'John Wesley Shipp',
        firstAppearanceAsSpeedster: 'The Flash 2x23 "The Race of His Life" '
    },
    {
        speedster: 'The Rival (Edward Clariss)',
        lightningColorsElectrokinesis: 'Red (Speed Force) [Philosopher\'s Stone]',
        universe: 'Earth-1',
        actoractress: 'Todd Lasance',
        firstAppearanceAsSpeedster: 'The Flash 3x01 "Flashpoint" '
    },
    {
        speedster: 'Trajectory (Eliza Harmon)',
        lightningColorsElectrokinesis: 'Yellow (V9) 🡒 Blue (Overdose V9)',
        universe: 'Earth-1',
        actoractress: 'Allison Paige',
        firstAppearanceAsSpeedster: 'The Flash 2x16 "Trajectory" '
    },
    {
        speedster: 'Music Meister',
        lightningColorsElectrokinesis: 'Orange (Speed Force) [Stolen]',
        universe: 'Unknown',
        actoractress: 'Darren Criss',
        firstAppearanceAsSpeedster: 'The Flash 3x17 "Duet" '
    },
    {
        speedster: 'The Flash (Oliver Queen)',
        lightningColorsElectrokinesis: 'Orange (Speed Force) [Rewritten Reality]',
        universe: 'Earth-1',
        actoractress: 'Stephen Amell',
        firstAppearanceAsSpeedster: 'The Flash 5x09 "Elseworlds, Part 1" '
    },
    {
        speedster: 'A.M.A.Z.O.',
        lightningColorsElectrokinesis: 'Orange (Speed Force) [Copied]',
        universe: 'Earth-1',
        actoractress: 'CGI',
        firstAppearanceAsSpeedster: 'The Flash 5x09 "Elseworlds, Part 1" '
    },
    {
        speedster: 'The Flash (Barry Allen)',
        lightningColorsElectrokinesis: 'Yellow (Speed Force)',
        universe: 'Earth-90',
        actoractress: 'John Wesley Shipp',
        firstAppearanceAsSpeedster: 'The Flash 5x09 "Elseworlds, Part 1" '
    },
    {
        speedster: 'Kid Flash (Wally West)',
        lightningColorsElectrokinesis: 'Yellow (Speed Force) [Philosopher\'s Stone]',
        universe: 'Earth-1',
        actoractress: 'Keiynan Lonsdale',
        firstAppearanceAsSpeedster: 'The Flash 3x01 "Flashpoint" '
    },
    {
        speedster: 'The Flash (Iris West-Allen)',
        lightningColorsElectrokinesis: 'Purple (Speed Force) [Melting Point]',
        universe: 'Earth-1',
        actoractress: 'Candice Patton',
        firstAppearanceAsSpeedster: 'The Flash 4x16 "Run Iris Run"'
    },
    {
        speedster: 'XS (Nora West-Allen)',
        lightningColorsElectrokinesis: 'Purple & Yellow (Speed Force) / Purple & Red (Negative Speed Force)',
        universe: 'Earth-1',
        actoractress: 'Jessica Parker Kennedy',
        firstAppearanceAsSpeedster: 'The Flash 4x20 "Therefore She Is"'
    },
    {
        speedster: 'The Flash (Gorilla Grodd)',
        lightningColorsElectrokinesis: 'Orange (Speed Force) [Mindscape Merge]',
        universe: 'Earth-Prime',
        actoractress: 'David Sobolov / Grant Gustin',
        firstAppearanceAsSpeedster: 'The Flash 6x13 "Grodd Friended Me"'
    }
];

module.exports.Abilities = {
    speedsters: {
        title1: 'Speed Force connection/Meta-human physiology',
        ability1: 'A Speedster\'s powers come from a connection to the Speed Force, this alters and supercharges their DNA, cells, and neurotransmitters, augmenting their physiology.',
        title2: 'Accelerated healing factor',
        ability2: 'Without treatment, most damage heals in hours if not minutes with no lingering signs. Even normally permanent damage, like paraplegia, is completely repaired in days.',
        title3: 'Bodily vibration',
        ability3: 'Speedsters can vibrate their body for various effects.',
        title4: 'Seismokinesis',
        ability4: 'By vibrating at varying frequencies and with different levels of force, speedsters can create small tremors to induce extreme amounts of jolt on any target they touch.',
        title5: 'Intangibility',
        ability5: 'By vibrating their molecules at the frequency of air, speedsters can physically pass through solid matter.',
        title6: 'Invisibility',
        ability6: 'Speedsters can vibrate their body so fast that they can no longer be perceived by the human eye.',
        title7: 'Electrokinesis',
        ability7: 'Speedsters can produce electricity in various colors, their Speed Force energy, from their body. It is commonly seen when running to boost their already immense speed to far higher levels.',
        title8: 'Speed Force sharing (Unique to Barry Allen)',
        ability8: 'Barry can expand his Speed Force aura to protect others he carries while moving at super speed.',
        title9: 'Superhuman strength',
        ability9: 'Speedsters physical strength has been heightened beyond that of normal human capacities.',
        title10: 'Superhuman durability',
        ability10: 'Speedsters possess inhuman resilience, most commonly seen from being unaffected by momentum build-up. They can take attacks and exertion, even survive impacts that would easily kill normal humans.',
        title11: 'Superhuman mental process',
        ability11: 'A Speedsters powers also make their system and thought processing able to take in and retain information just as fast and efficiently. Even while using their raw speed, they can clearly think, react to events, and perform actions long before normal humans can perceive them.',
        title12: 'Superhuman perceptions',
        ability12: 'A Speedsters senses are also enhanced. This allows them to perceive the world as if it is nearly frozen. They can see and hear normally, even while moving at speeds faster than sound, where this would normally be impossible.',
        title13: 'Superhuman speed',
        ability13: 'Speedsters can move at such vast speeds, indeterminable to the naked eye.',
        title14: 'Superhuman agility',
        ability14: 'Speedsters possess flawless coordination, equilibrium and dexterity, they can change direction with immediate sharp turns without sliding or losing balance and instantly stop running on the spot.',
        title15: 'Superhuman reflexes',
        ability15: 'A Speedsters reaction time is augmented to superhuman levels, allowing them to react to danger and events far faster than normal humans.',
        title16: 'Superhuman momentum',
        ability16: 'Speedsters can generate great amounts of physical force through kinetic energy, simulating superhuman strength, even in a stationary position.',
        title17: 'Aerokinesis',
        ability17: 'Speedsters can use their speed to generate air flows on various levels and for various effects.',
        title18: 'Time travel',
        ability18: 'The kinetic energy buildup from a speedsters speed can allow them to breach the space-time continuum, allowing them to physically enter the Speed Force and travel through time.',
        title19: 'Time reversal (Unique to Nora West-Allen)',
        ability19: 'Nora is able to reverse time around her while running, remaining completely unaffected.',
        title20: 'Inter-dimensional travel',
        ability20: 'Speedsters can move fast enough to break open portals between dimensions, allowing them to travel to different universes.',
        title21: 'Speed mirages',
        ability21: 'Speedsters can generate illusions of themselves to make it appear as if they were in many places at once, when in reality they are simply bouncing back and forth too fast for the human mind to perceive the difference.',
        title22: 'Temporal regression (Unique to Barry Allen)',
        ability22: 'With his ability to shift through time, Barry can also reverse the flow effects while running at a certain speed, while he remains completely unaffected.',
        title23: 'Temporal dilution (Unique to Barry Allen & Nora West-Allen)',
        ability23: 'By generating enough energy, Barry and Nora can move so fast that time essentially slows down relative to them, to a complete standstill.',
        title24: 'Time remnant construct',
        ability24: 'Speedsters are able to "create" a time remnant by traveling back to moments before their current-self time travels, hailing from a future that no longer exists. This allows them to be two places at once.',
        title25: 'Temporal awareness',
        ability25: 'Speedsters are able to subconsciously detect when other speedsters enter the Speed Force to time travel.',
        title26: 'Speed Force awareness',
        ability26: 'With concentration, speedsters can sense the Speed Force in another speedster\'s system.',
        title27: 'Superhuman stamina',
        ability27: 'Speedsters can handle the stresses of extreme racing without noticeable distress, letting them function much longer than normal humans unhindered. Their enhanced stamina is due to their augmented physiology, which builds up little to no lactic acid or fatigue toxins.'
    },
    vibers: {
        title1: 'Meta-human physiology',
        ability1: 'Vibers possess altered DNA and physiology to access dimensional energy.',
        title2: 'Dimensional energy manipulation',
        ability2: 'Vibers have a psychic link to the natural energies of reality, allowing them to connect with various vibrations of the multiverse and manipulate them for various effects.',
        title3: 'Dimensional awareness',
        ability3: 'Known as "vibing", vibers can perceive various events throughout time and space, letting them see into the past and future as well as parallel dimensions, even into the very Speed Force itself.',
        title4: 'Inter-dimensional travel',
        ability4: 'With their natural connection to the multiverse, vibers can open portals to other dimensions. Being a noticeably more advanced ability, they are shown to need focus and a proper awareness of their intended target.',
        title5: 'Vibrational blasts',
        ability5: 'Vibers are able to generate powerful blue or red concussive blasts of vibrations from their hands capable of propelling full-grown humans through the air.',
        title6: 'Mental connection',
        ability6: 'Vibers are connected by their powers and are able to observe each other if they\'re skilled enough.'
    },
    kryptonians: {
        title1: 'Kryptonian physiology',
        ability1: 'A kryptonians capabilities are no greater than those of a human. However, once charged by the energy spectrum of a yellow sun, they become able to perform various inhuman feats.',
        title2: 'Solar energy absorption',
        ability2: 'Kryptonian powers are dependent on the energy spectrum from a yellow sun, their body is able to constantly and passively absorb such energy while exposed to it, essentially keeping their reserves fully charged near-constantly.',
        title3: 'Accelerated healing factor',
        ability3: 'Kryptonian metabolism is tremendously enhanced by solar energy, allowing accelerated healing abilities and burning calories at a superhuman rate, making them practically immune to becoming fat or obese.',
        title4: 'Contaminant immunity',
        ability4: 'Kryptonians have an immunity to all forms of disease and contaminants on Earth.',
        title5: 'Resurrection',
        ability5: 'After they die, kryptonians are able to self-resurrect by absorbing solar energy from flora in their vicinity.',
        title6: 'Flight',
        ability6: 'Kryptonians are able to manipulate their own gravitational field to generate thrust and propel themselves through the air, often at hyper-sonic speeds, much faster than they can travel by foot.',
        title7: 'Sleep flight',
        ability7: 'Kryptonians have the ability to float in the air while they sleep.',
        title8: 'Levitation',
        ability8: 'Kryptonians can levitate using their flight abilities.',
        title9: 'Heat vision',
        ability9: 'By concentrating every solar energy reserve they have in their body, kryptonians can emit blue or red energy beams of variable intensity and temperature from their eyes.',
        title10: 'Invulnerability',
        ability10: 'Kryptonians are essentially invulnerable to all Earthly weapons, with bullets simply ricocheting whenever they come into contact with their skin.',
        title11: 'Extreme heat resistance',
        ability11: 'Kryptonians feel no pain when exposed to extreme heat.',
        title12: 'Self-sustenance',
        ability12: 'Due to the effects of a yellow sun, a kryptonians physical needs are greatly reduced.',
        title13: 'Atmospheric adaption',
        ability13: 'While kryptonians do require oxygen, their physicality and exposure to a yellow sun allows them to survive while inhaling more harsh forms of it such as the thin, highly CO2-concentrated, atmosphere of Mars.',
        title14: 'Reverse photosynthesis',
        ability14: 'Kryptonians are capable of draining solar energy from plants even without a direct source of light.',
        title15: 'Super vision',
        ability15: 'Kryptonians are able to see very far distances, presumably at peak human or low superhuman levels. They are even able to see clearly in the dark.',
        title16: 'X-ray vision',
        ability16: 'Kryptonians possess the ability to see through objects, except for lead.',
        title17: 'Super breath',
        ability17: 'Kryptonians are able to exhale powerful gusts of air from their mouth which are similar to force winds. They can also cause the temperature of their breath to drop, therefore able to freeze nearly anything.',
        title18: 'Super hearing',
        ability18: 'Kryptonians have super-sensitive ears that can perfectly pick up sounds from miles away and even through structures.',
        title19: 'Super speed',
        ability19: 'Kryptonians possess the ability to move at hyper-sonic speeds, both through flight and on foot.',
        title20: 'Accelerated perception',
        ability20: 'While using their super speed, Kryptonians see everything much slower, allowing them to move with precision and accuracy within very fast moments.',
        title21: 'Super reflexes',
        ability21: 'A kryptonians reflexes are so fast, that they can respond to attacks within seconds.',
        title22: 'Time deceleration',
        ability22: 'When a kryptonian and a speedster (or another kryptonian) run/fly around the Earth in opposite directions, they are able to slow the Earth\'s rotation, along with time itself',
        title23: 'Super strength',
        ability23: 'A kryptonians strength is enhanced under a yellow sun, enough to easily kill a normal human if they were to attack them directly.',
        title24: 'Thunderclap',
        ability24: 'When kryptonians use their super strength to clap their hands together, it creates a powerful shock-wave that throws enemies back.',
        title25: 'Super jumping/leaping',
        ability25: 'Kryptonians are able to jump several feet off the ground and leap several stories in a single bound without having to fly.',
        title26: 'Super stamina',
        ability26: 'Kryptonians can run, fight or fly for long periods of time, without getting tired.',
        title27: 'Extended longevity',
        ability27: 'A Kryptonians life span is considerably longer than a humans and they likewise age much slower.',
        title28: 'Telepathy immunity',
        ability28: 'Kryptonians are immune to most forms of telepathic powers.',
        title29: 'Power bestowal via electricity',
        ability29: 'If a kryptonian is holding a person while electrocuted by lightning, their kryptonian physiology allows them to affect the person, giving the person strange abilities.',
    }
};

module.exports.Timeline = [
    'Because of your interferences, the President of the United States is now a resurrected Michael Jackson. ',
    'Your interference has caused the Green Lantern to make One Billion at the Box Office, what have you done.',
    'The effect of you interfering with the timeline has caused Season 4 of Arrow to not exist, well done.',
    'Interfering with the ti..meline has caused me to not be inven….ted. I don’t feel so go…………',
    'Because of your interfering, Endgame is not the highest grossing film of all time, Avatar still is, how awful.',
    'Your interference has caused the Nazi’s to be lead under the guidance of a drunk Mick Rory.',
    'Because of your interferences, there is now a musical about Superman called, “Super-Musical”',
    'Interfering with the timeline caused the Mona Lisa to now be a painting of Leonardo Da Vinci’s feet',
    'The effect of you interfering with the timeline has caused Julius Caesar to be murdered by Mario and Luigi. Mamma Mia!',
    'Because of your interference with the timeline, men are now the gender that give birth, and it is very painful.',
    'Your interference has caused the future to be destroyed by Radioactive Kittens',
    'Interfering with the timeline has caused Joan of Arc to instead be John of Arc',
    'The effect of your interfering has caused a Pac-Man console to be found by Genghis Khan, who stopped conquering to get a perfect high score.',
    'Because of your reckless interferences with the timeline, Abraham Lincoln now wears his hat because a small green alien lives under it.',
    'Your interference with the timeline has caused the King of England to now be a Jewish Leprechaun',
    'Interfering with the timeline has caused O.J. Simpson to become a black market motivational speaker on how to get away with crimes',
    'Due to your interfering with the timeline, Disney now rules the entire planet with an iron fist.',
    'Interfering with the timeline has caused Freddie Mercury to have come back from the dead, only to kill the person who invented Dubstep',
    'Your interference with the timeline has caused the game ‘Crisis on Earth One’ to be released, the whole world salutes you.',
    'Because of your interferences with the timeline, The Lion King is now a movie about a king who has a pet lion.',
    'Your interference with the timeline has caused World Peace, good job!',
    'Due to your reckless interferences with the timeline, the world is now run under the eyes of an all-seeing Axolotl.',
    'Your interferences with the timeline have caused the film ‘Top Gun’ to never have been made. Oh dear, what have you done!',
    'Because of your interferences with the timeline, the Soviet Union was now run by Willy Wonka in a Santa Claus costume.',
    'Due to your interference with the timeline has caused Easter to now be celebrated with Chocolate Swordfish.',
    'Your interference with the timeline has caused you to get superpowers.',
    'Interfering with the timeline has caused to become married to Jessica Parker Kennedy. Well done!Because of your reckless interferences with the timeline, Han Solo was now played by Eddie Murphy.',
    'Due to your interferences with the timeline, Ice-cream is now very toxic and dangerous, and kids are now enjoying bowls of asbestos.',
    'The effect of you Interfering with the timeline has caused the Statue of Liberty to now be made entirely of Lego.',
    'Your interfering with the timeline has caused Pirates and Mermaids to have been in a 300 year war, ending with the Mermaids viciously murdering all of the pirates.',
    'Interfering with the timeline has caused Sasquatch to now be hunted for its delicious meat.   ',
    'Due to your reckless interferences with the timeline, the most spoken language in the world is now Japanese… ひざはおいしですよ。'
];


module.exports.API = {
    API: {
        status: 'Gideon API online and functional!'
    }
};

module.exports.TheBoys = [
    {quote: "I'll tell you who you are, you're a moron. _Translucent_ doesn't even mean _invisible_, it means _semi-transparent_.", author: "William Butcher", img: "https://imgix.ranker.com/user_node_img/50098/1001941889/original/billy-butcher-photo-u2?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "Just 'cause you fall on your ass doesn't mean you have to stay there.", author: "Hugh Campbell Jr.", img: "https://imgix.ranker.com/user_node_img/50098/1001941897/original/hughie-campbell-photo-u2?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "...", author: "Black Noir", img: "https://imgix.ranker.com/user_node_img/50098/1001941891/original/black-noir-photo-u2?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "See, people love that cozy feeling Supes give them... but if you knew half the shit they get up to... Fuckin' diabolical. But then, that's where I come in. To spank the bastards when they get out of line.", author: "William Butcher", img: "https://imgix.ranker.com/user_node_img/50098/1001941889/original/billy-butcher-photo-u2?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "If I'm gonna make a difference, I just feel more comfortable doing it on a smaller scale. I'm a motherfucker with a heart.", author: "Marvin T. Milk", img: "https://imgix.ranker.com/user_node_img/50098/1001941899/original/mother_s-milk-photo-u3?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "I know a little about a lot of things. I'm a gunrunner by trade, but, as you can see, I've developed a certain niche.", author: "Serge", img: "https://imgix.ranker.com/user_node_img/50098/1001941895/original/-frenchie-photo-u2?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "I'm the Homelander. And I can do whatever the fuck I want.", author: "Homelander", img: "https://static.wikia.nocookie.net/amazons-the-boys/images/6/60/Homelander_S2.jpg/revision/latest?cb=20200808192351"},
    {quote: "You and your corporation are fucked. Unequivocally, unilaterally fucked.", author: "Susan Raynor", img: "https://imgix.ranker.com/user_node_img/50098/1001941904/original/susan-raynor-photo-u1?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "Since when did 'hopeful' and 'naive' become the same thing? I mean, why would you get into this business if not to save the world? That's all I have ever wanted.", author: "Annie January", img: "https://imgix.ranker.com/user_node_img/50098/1001946199/original/behind-the-scenes-photo-u1?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "My superpower ain't invisiblity - it's reading people. Watching them when they think they're alone. I see people for who they really are.", author: "Translucent", img: "https://imgix.ranker.com/user_node_img/50098/1001941908/original/translucent-photo-u1?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "Why have average when you can have extraordinary?", author: "Madelyn Stillwell", img: "https://imgix.ranker.com/user_node_img/50098/1001941898/original/madelyn-stillwell-photo-u2?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "You don't have the fight. You never have. Neither do I.", author: "Hugh Campbell Sr.", img: "https://imgix.ranker.com/user_node_img/50098/1001942149/original/hugh-campbell-photo-u1?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "Never let them see you like this.", author: "Maggie Shaw", img: "https://imgix.ranker.com/user_node_img/50098/1001941902/original/-queen-maeve-photo-u2?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "Don't make me use that gas on you, huh, pumpkin?", author: "Cherie", img: "https://imgix.ranker.com/user_node_img/50098/1001941892/original/cherie-photo-u1?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "They only call me when there's trouble at a dock. Or a river. Or a lake. A canal. A jetty. I could be doing so much more...", author: "Kevin Moskowitz", img: "https://imgix.ranker.com/user_node_img/50098/1001941905/original/the-deep-photo-u2?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "Oh, and if someone sticks a dick in your mouth, bite it off. Pippi Longstocking would bite a D, that's for damned sure.", author: "Klara Risinger", img: "https://imgix.ranker.com/user_node_img/50115/1002285633/original/1002285633-photo-u1?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "For the last half-century you have been feeding the American people that your Superheroes were chosen by God", author: "Susan Raynor", img: "https://imgix.ranker.com/user_node_img/50098/1001941904/original/susan-raynor-photo-u1?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "At least I don't have to kiss your ass anymore.", author: "Ashley Barret", img: "https://imgix.ranker.com/user_node_img/50098/1001941909/original/ashley-barrett-photo-u2?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "If there's a way to screw this up, you'll find it.", author: "Grace Mallory", img: "https://imgix.ranker.com/user_node_img/50115/1002285627/original/1002285627-photo-u1?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "Nobody wants the second fastest man in The Seven.", author: "Reggie Franklin", img: "https://imgix.ranker.com/user_node_img/50098/1001941483/original/a-train-photo-u1?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "I just wanted to make my dad proud.", author: "Lamplighter", img: "https://imgix.ranker.com/user_node_img/50115/1002285636/original/1002285636-photo-u1?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "Come on, you're not the first person to call me a cunt, Mr. Butcher. I'm starting to think it's like a badge of honor.", author: "Victoria Neuman", img: "https://imgix.ranker.com/user_node_img/50115/1002285637/original/1002285637-photo-u1?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "Girls do get it done.", author: "Serge", img: "https://imgix.ranker.com/user_node_img/50098/1001941895/original/-frenchie-photo-u2?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "It's not even gay if it's with yourself.", author: "Doppelgänger", img: "https://imgix.ranker.com/user_node_img/50115/1002285631/original/1002285631-photo-u1?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "Don't be a pussy. Laser my fucking tits.", author: "Klara Risinger", img: "https://imgix.ranker.com/user_node_img/50115/1002285633/original/1002285633-photo-u1?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "Moral compromise does have its privileges.", author: "Jonah Vogelbaum", img: "https://imgix.ranker.com/user_node_img/50115/1002285640/original/1002285640-photo-u1?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "There are no secrets from me.", author: "Mesmer", img: "https://imgix.ranker.com/user_node_img/50098/1001942189/original/mesmer-photo-u1?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "For an extra grand, I'll let you chop off my dick.", author: "Gecko", img: "https://imgix.ranker.com/user_node_img/50115/1002285620/original/1002285620-photo-u1?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "I don't bite. Unless you want me to...", author: "Popclaw", img: "https://imgix.ranker.com/user_node_img/50098/1001941900/original/popclaw-_charlotte_-photo-u1?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: " How do I get to hold the whole world in my loving embrace? Why were we chosen? Because of the Lord. Because we were born with this power. Because we believe.", author: "Ezekiel", img: "https://imgix.ranker.com/user_node_img/50098/1001941894/original/ezekiel-photo-u1?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "People would give anything to be what you are. I thought I did what was right.", author: "Donna January", img: "https://imgix.ranker.com/user_node_img/50098/1001941893/original/donna-january-photo-u2?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "I'm supposed to be this hero, idol symbol, but I don't know what the hell I'm doing.", author: "Annie January", img: "https://imgix.ranker.com/user_node_img/50098/1001946199/original/behind-the-scenes-photo-u1?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "Just remember who your friends and who your enemies are.", author: "William Butcher", img: "https://imgix.ranker.com/user_node_img/50098/1001941889/original/billy-butcher-photo-u2?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "What's Sporty Spice up to?", author: "William Butcher", img: "https://imgix.ranker.com/user_node_img/50098/1001941889/original/billy-butcher-photo-u2?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "Pardon my French, fuck those fuckers.", author: "William Butcher", img: "https://imgix.ranker.com/user_node_img/50098/1001941889/original/billy-butcher-photo-u2?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "It doesn’t even matter to you because what you can’t stand is in my blood. I’m subhuman to you. Only good Supe is a dead Supe, right?", author: "Annie January", img: "https://imgix.ranker.com/user_node_img/50098/1001946199/original/behind-the-scenes-photo-u1?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "I think A-Train sabotaged me my entire career. Well, you do think you’re better than me. And I fantasize about drowning you over and over again.", author: "Kevin Moskowitz", img: "https://imgix.ranker.com/user_node_img/50098/1001941905/original/the-deep-photo-u2?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "See? I told you I don’t break easy.", author: "Klara Risinger", img: "https://imgix.ranker.com/user_node_img/50115/1002285633/original/1002285633-photo-u1?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "If any of these Moonies are gonna help you get back in The Seven, and that’s a big if, then you’re gonna need a woman to tell everyone that you’re not a complete piece of shit", author: "Maggie Shaw", img: "https://imgix.ranker.com/user_node_img/50098/1001941902/original/-queen-maeve-photo-u2?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "So you want to take me on do ya? Think you got the bollocks? Well come on then cunt.", author: "William Butcher", img: "https://imgix.ranker.com/user_node_img/50098/1001941889/original/billy-butcher-photo-u2?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "If you served with our amazing soldiers like I have, you would know that freedom comes at a price.", author: "Homelander", img: "https://static.wikia.nocookie.net/amazons-the-boys/images/6/60/Homelander_S2.jpg/revision/latest?cb=20200808192351"},
    {quote: "I used to be angry, insecure and unsure. But thanks to the Church of the Collective, I now know the kind of man I want to be. The kind of man who calls out injustice when he sees it.", author: "Kevin Moskowitz", img: "https://imgix.ranker.com/user_node_img/50098/1001941905/original/the-deep-photo-u2?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "Go be a monster.", author: "Serge", img: "https://imgix.ranker.com/user_node_img/50098/1001941895/original/-frenchie-photo-u2?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "She’s no kitten. She can make her own choices.", author: "Cherie", img: "https://imgix.ranker.com/user_node_img/50098/1001941892/original/cherie-photo-u1?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "The thing that kills me is that your wife is alive. She just doesn’t want you, that’s all.", author: "Hugh Campbell Jr.", img: "https://imgix.ranker.com/user_node_img/50098/1001941897/original/hughie-campbell-photo-u2?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "If they want a lesbian Ken doll, they can find someone else.", author: "Elena", img: "https://static.wikia.nocookie.net/amazons-the-boys/images/7/79/Elena.png/revision/latest/scale-to-width-down/279?cb=20200904064508"},
    {quote: "Look, everyone is upset about Compound V. I mean, someone was so upset, they leaked it to the press. Can you imagine how angry that person is? Whoever they are?", author: "Klara Risinger", img: "https://imgix.ranker.com/user_node_img/50115/1002285633/original/1002285633-photo-u1?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "I used to think that you, me and Becca would grow old together. Bloody stupid. Turns out she don’t..", author: "William Butcher", img: "https://imgix.ranker.com/user_node_img/50098/1001941889/original/billy-butcher-photo-u2?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "I just thought you should know Liberty, that Supe that Raynor was looking into, turns out it’s Stormfront.", author: "Hugh Campbell Jr.", img: "https://imgix.ranker.com/user_node_img/50098/1001941897/original/hughie-campbell-photo-u2?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "We can’t afford to feel good or to feel safe or to let our guard down.", author: "Annie January", img: "https://imgix.ranker.com/user_node_img/50098/1001946199/original/behind-the-scenes-photo-u1?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "You spent $273 million on that 'Saving America' bullshit, and I am running circles around you with five guys on laptops churning out memes. I practicall pay them with Arby’s gift cards. You can’t win the whole country anymore. No one can.", author: "Klara Risinger", img: "https://imgix.ranker.com/user_node_img/50115/1002285633/original/1002285633-photo-u1?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "I’m the face of The Seven. Not you.", author: "Homelander", img: "https://static.wikia.nocookie.net/amazons-the-boys/images/6/60/Homelander_S2.jpg/revision/latest?cb=20200808192351"},
    {quote: "Oh, is it so hard to believe that I want you two to be happy? And in love? Honestly Maeve, I am really, really happy for you.", author: "Homelander", img: "https://static.wikia.nocookie.net/amazons-the-boys/images/6/60/Homelander_S2.jpg/revision/latest?cb=20200808192351"},
    {quote: "I walk around The Seven Tower with this knot in my gut. Just wondering if Homelander is waiting around every corner to kill me. It’s like living with a loaded gun in my face.", author: "Annie January", img: "https://imgix.ranker.com/user_node_img/50098/1001946199/original/behind-the-scenes-photo-u1?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "Hughie Campbell broke my fucking heart. Worse than anyone ever has. And part of me wants to blast his fucking face off, so no, I’m not with him.", author: "Annie January", img: "https://imgix.ranker.com/user_node_img/50098/1001946199/original/behind-the-scenes-photo-u1?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "You snooze, you lose Gramps.", author: "Klara Risinger", img: "https://imgix.ranker.com/user_node_img/50115/1002285633/original/1002285633-photo-u1?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "Open your eyes, I like to see the light go out.", author: "Klara Risinger", img: "https://imgix.ranker.com/user_node_img/50115/1002285633/original/1002285633-photo-u1?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "Hands in the air, like you just don’t care. Kill. Do it.", author: "Homelander", img: "https://static.wikia.nocookie.net/amazons-the-boys/images/6/60/Homelander_S2.jpg/revision/latest?cb=20200808192351"},
    {quote: "Your gill is showing. Cover it up, it’s disgusting.", author: "Homelander", img: "https://static.wikia.nocookie.net/amazons-the-boys/images/6/60/Homelander_S2.jpg/revision/latest?cb=20200808192351"},
    {quote: "Hughie’s not going to make it. And you need that kid, more than any one of us. He’s your canary. You let your canary die, how you gonna know when you’ve gone too far?", author: "Marvin T. Milk", img: "https://imgix.ranker.com/user_node_img/50098/1001941899/original/mother_s-milk-photo-u3?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "It doesn’t matter who made us, or how we got here, the point is we are here. Together. Family. You guys, you are my real family.", author: "Homelander", img: "https://static.wikia.nocookie.net/amazons-the-boys/images/6/60/Homelander_S2.jpg/revision/latest?cb=20200808192351"},
    {quote: "You’re my second wind.", author: "Hugh Campbell Jr.", img: "https://imgix.ranker.com/user_node_img/50098/1001941897/original/hughie-campbell-photo-u2?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "A stranger is just a friend you haven’t met yet.", author: "William Butcher", img: "https://imgix.ranker.com/user_node_img/50098/1001941889/original/billy-butcher-photo-u2?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "The night our parents were murdered, Kimiko just stopped talking.", author: "Kenji Myashiro", img: "https://static.wikia.nocookie.net/amazons-the-boys/images/a/a2/Kenji.PNG/revision/latest/scale-to-width-down/310?cb=20200907210145"},
    {quote: "When we’re all done here, I’ll buy you a nice, big, family size bottle of top shelf lube and I’ll tickle your balls till you beg me to stop and even then I won’t.", author: "William Butcher", img: "https://imgix.ranker.com/user_node_img/50098/1001941889/original/billy-butcher-photo-u2?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "My mom said it was a gift. That I was born this way. But it wasn’t. It didn’t have to be this way. I could have been normal.", author: "Kevin Moskowitz", img: "https://imgix.ranker.com/user_node_img/50098/1001941905/original/the-deep-photo-u2?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "You don’t fuck with the money. You never fuck with the money.", author: "Reggie Franklin", img: "https://imgix.ranker.com/user_node_img/50098/1001941483/original/a-train-photo-u1?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "You write all women as either unknowable Hitchcock bitches or Michael Bay fuck dolls. I get that a lifetime of jerking off to Transformers didn’t exactly make you popular with the ladies, but a little effort would be nice.", author: "Klara Risinger", img: "https://imgix.ranker.com/user_node_img/50115/1002285633/original/1002285633-photo-u1?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "You come between me and my missus again, I’ll fucking kill you.", author: "William Butcher", img: "https://imgix.ranker.com/user_node_img/50098/1001941889/original/billy-butcher-photo-u2?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "Shining Light fights for injustice.", author: "Kenji Myashiro", img: "https://static.wikia.nocookie.net/amazons-the-boys/images/a/a2/Kenji.PNG/revision/latest/scale-to-width-down/310?cb=20200907210145"},
    {quote: "Becca’s alive.", author: "William Butcher", img: "https://imgix.ranker.com/user_node_img/50098/1001941889/original/billy-butcher-photo-u2?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "It’s like V has infected you with a raging case of vagina.", author: "William Butcher", img: "https://imgix.ranker.com/user_node_img/50098/1001941889/original/billy-butcher-photo-u2?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "Kimiko is one of us.", author: "Marvin T. Milk", img: "https://imgix.ranker.com/user_node_img/50098/1001941899/original/mother_s-milk-photo-u3?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "I love you son.", author: "Homelander", img: "https://static.wikia.nocookie.net/amazons-the-boys/images/6/60/Homelander_S2.jpg/revision/latest?cb=20200808192351"},
    {quote: "Mom says being lonely makes you know yourself better.", author: "Ryan Butcher", img: "https://static.wikia.nocookie.net/amazons-the-boys/images/3/37/Ryan_Butcher.png/revision/latest?cb=20200905091441"},
    {quote: "Sometimes it’s hard being superior to every other single person on the planet, sometimes it is isolating. And gods, should not have to feel that kind of pain. Because that is what we are, Ryan. You and me, are gods.", author: "Homelander", img: "https://static.wikia.nocookie.net/amazons-the-boys/images/6/60/Homelander_S2.jpg/revision/latest?cb=20200808192351"},
    {quote: "The things that I’ve watched him do, the things he made me do…", author: "Maggie Shaw", img: "https://imgix.ranker.com/user_node_img/50098/1001941902/original/-queen-maeve-photo-u2?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "Homelander and I went to this Oscar party for 12 Years A Slave. There was this producer, he swapped place cards so he could sit next to me. And he chatted me up all night. Two days later, there’s a fire in his office. They found his head in one room and his torso in another.", author: "Maggie Shaw", img: "https://imgix.ranker.com/user_node_img/50098/1001941902/original/-queen-maeve-photo-u2?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "If you threaten me again, I’m going to make sure they know you’re the one that took it.", author: "Gecko", img: "https://imgix.ranker.com/user_node_img/50115/1002285620/original/1002285620-photo-u1?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "I mean this in the nicest possible way, but I don’t need some fucking Vought Spy Brabie sniffing around to see whether I’m a team player.", author: "Klara Risinger", img: "https://imgix.ranker.com/user_node_img/50115/1002285633/original/1002285633-photo-u1?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "How does everyone feel about you helping your traitor fucking boyfriend escape?  Or maybe you didn’t mention that part.", author: "Reggie Franklin", img: "https://imgix.ranker.com/user_node_img/50098/1001941483/original/a-train-photo-u1?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "Why does it matter is heroes have a dick or a vag? I mean, shouldn’t we all just, you know, be competent at our jobs? I don’t think girls to it better. I think chicks and dicks are in it together.", author: "Klara Risinger", img: "https://imgix.ranker.com/user_node_img/50115/1002285633/original/1002285633-photo-u1?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "We’ve never had three women in The Seven before. This is a moment. Girls get it done.", author: "Ashley Barret", img: "https://imgix.ranker.com/user_node_img/50098/1001941909/original/ashley-barrett-photo-u2?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "She was already dead when I blew her up.", author: "William Butcher", img: "https://imgix.ranker.com/user_node_img/50098/1001941889/original/billy-butcher-photo-u2?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "We got a Supe Terrorist, Rayner’s blown her canister, and we’re the most wanted cunts in the country. But don’t you worry. Daddy’s home.", author: "William Butcher", img: "https://imgix.ranker.com/user_node_img/50098/1001941889/original/billy-butcher-photo-u2?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "Don’t lie to me, not again.", author: "Annie January", img: "https://imgix.ranker.com/user_node_img/50098/1001946199/original/behind-the-scenes-photo-u1?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "Well, I’ve come to see my son.", author: "Homelander", img: "https://static.wikia.nocookie.net/amazons-the-boys/images/6/60/Homelander_S2.jpg/revision/latest?cb=20200808192351"},
    {quote: "The point is, you are under a misconception that we are a superhero company. We are not. What we are, really, is a pharmaceutical company. And you are not our most valuable asset. That would be our confidential formula for Compound V. Which you, man-child that you are, released into the wild.", author: "Stan Edgar", img: "https://imgix.ranker.com/user_node_img/50115/1002285647/original/1002285647-photo-u1?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "I need you to go into the labs on 67, and steal me a sample of compound V.", author: "Annie January", img: "https://imgix.ranker.com/user_node_img/50098/1001946199/original/behind-the-scenes-photo-u1?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "So, maybe I can’t be Lee Marvin. But I can be Harry Potter. Or, you know, John Connor or what’s her name from The Hunger Games. The point is, I can be that person that nobody thinks is awesome, but it turns out, they’re kind of fucking awesome", author: "Hugh Campbell Jr.", img: "https://imgix.ranker.com/user_node_img/50098/1001941897/original/hughie-campbell-photo-u2?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "You’ve been walking around for days like you want to kick my ass, so do it already.", author: "Hugh Campbell Jr.", img: "https://imgix.ranker.com/user_node_img/50098/1001941897/original/hughie-campbell-photo-u2?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "What makes you think I would ever allow a cripple into The Seven?", author: "Homelander", img: "https://static.wikia.nocookie.net/amazons-the-boys/images/6/60/Homelander_S2.jpg/revision/latest?cb=20200808192351"},
    {quote: "I am going to fill Mrs. Stillwell's shoes as best I can.", author: "Ashley Barret", img: "https://imgix.ranker.com/user_node_img/50098/1001941909/original/ashley-barrett-photo-u2?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "You think water is suppose to be fun? Try swimming in the Mariana Trench, you little fucking idiots. Yeah, not so fun there. No, its dark and its cold. And you’re so alone.", author: "Kevin Moskowitz", img: "https://imgix.ranker.com/user_node_img/50098/1001941905/original/the-deep-photo-u2?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "I’m wanted and you’re kind of super famous.", author: "Hugh Campbell Jr.", img: "https://imgix.ranker.com/user_node_img/50098/1001941897/original/hughie-campbell-photo-u2?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "For today, we mourn a fallen member of The Seven. Translucent. Murdered in cold blood by the cartel Super Terrorist El Diablo.", author: "Homelander", img: "https://static.wikia.nocookie.net/amazons-the-boys/images/6/60/Homelander_S2.jpg/revision/latest?cb=20200808192351"},
    {quote: "The truth is, our weakness is the same as anyone’s. It’s people. The people we care about. So I say, cut them loose. For your good and for theirs. That way you’re really bulletproof.", author: "Maggie Shaw", img: "https://imgix.ranker.com/user_node_img/50098/1001941902/original/-queen-maeve-photo-u2?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "You ever touch me again, I will burn your eyes out!", author: "Annie January", img: "https://imgix.ranker.com/user_node_img/50098/1001946199/original/behind-the-scenes-photo-u1?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "Translucent's always been my favorite.", author: "William Butcher", img: "https://imgix.ranker.com/user_node_img/50098/1001941889/original/billy-butcher-photo-u2?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "We'll cross that bridge when we burn it.", author: "William Butcher", img: "https://imgix.ranker.com/user_node_img/50098/1001941889/original/billy-butcher-photo-u2?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "I bet you'd thank a supe if they shat on your mum's best china.", author: "William Butcher", img: "https://imgix.ranker.com/user_node_img/50098/1001941889/original/billy-butcher-photo-u2?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "Hughie, you've done a murder. Comparatively speaking this will be a piece of cake.", author: "William Butcher", img: "https://imgix.ranker.com/user_node_img/50098/1001941889/original/billy-butcher-photo-u2?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "We didn't bring him here for a fucking Happy Meal.", author: "William Butcher", img: "https://imgix.ranker.com/user_node_img/50098/1001941889/original/billy-butcher-photo-u2?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "I've got my phone linked to the Find My Shithead Friends app.", author: "William Butcher", img: "https://imgix.ranker.com/user_node_img/50098/1001941889/original/billy-butcher-photo-u2?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "I just had to pop down to the shop. I was running a bit low on mind your own fucking business.", author: "William Butcher", img: "https://imgix.ranker.com/user_node_img/50098/1001941889/original/billy-butcher-photo-u2?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "When you put them together, they're the goddamn fucking Spice Girls", author: "William Butcher", img: "https://imgix.ranker.com/user_node_img/50098/1001941889/original/billy-butcher-photo-u2?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "Now you’re just another useless fucking blind guy.", author: "Homelander", img: "https://static.wikia.nocookie.net/amazons-the-boys/images/6/60/Homelander_S2.jpg/revision/latest?cb=20200808192351"},
    {quote: "You are dispensable, which means you answer to me.", author: "Homelander", img: "https://static.wikia.nocookie.net/amazons-the-boys/images/6/60/Homelander_S2.jpg/revision/latest?cb=20200808192351"},
    {quote: "If you’re the fucking reason I can’t finish that Vermont Country Dollhouse, I will fucking end you.", author: "Marvin T. Milk", img: "https://imgix.ranker.com/user_node_img/50098/1001941899/original/mother_s-milk-photo-u3?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "You are not a soldier, you’re not a spy. You’re just a kid that sells stereo equipment.", author: "Marvin T. Milk", img: "https://imgix.ranker.com/user_node_img/50098/1001941899/original/mother_s-milk-photo-u3?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "I thought we were friends.", author: "Gecko", img: "https://imgix.ranker.com/user_node_img/50115/1002285620/original/1002285620-photo-u1?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "I’m sorry but we’re not anything.", author: "Annie January", img: "https://imgix.ranker.com/user_node_img/50098/1001946199/original/behind-the-scenes-photo-u1?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "As if Homelander and Maeve were gonna eat MREs and piss in a ditch with the rest of the grunts.", author: "Klara Risinger", img: "https://imgix.ranker.com/user_node_img/50115/1002285633/original/1002285633-photo-u1?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "Not even Madelyn would have dared to try and pull this kind of shit.", author: "Homelander", img: "https://static.wikia.nocookie.net/amazons-the-boys/images/6/60/Homelander_S2.jpg/revision/latest?cb=20200808192351"},
    {quote: "While you are preening at the Golden Globes, we are running around like maniacs trying to clean up the mess you made.", author: "Stan Edgar", img: ""},
    {quote: "When I was his age I was breaking the sound barrier. He can’t even throw a fastball.", author: "Homelander", img: "https://static.wikia.nocookie.net/amazons-the-boys/images/6/60/Homelander_S2.jpg/revision/latest?cb=20200808192351"},
    {quote: "Becca we had a deal. A deal that is alive and well and running around as free as a goddamn bird.", author: "Homelander", img: "https://static.wikia.nocookie.net/amazons-the-boys/images/6/60/Homelander_S2.jpg/revision/latest?cb=20200808192351"},
    {quote: "We can do whatever we want and no one can stop us. That is a good feeling. A really good feeling.", author: "Homelander", img: "https://static.wikia.nocookie.net/amazons-the-boys/images/6/60/Homelander_S2.jpg/revision/latest?cb=20200808192351"},
    {quote: "You were right. I’m not gonna get bored and move on. I’m not going anywhere. So feel free to tell Dr. Park to go fuck himself.", author: "Homelander", img: "https://static.wikia.nocookie.net/amazons-the-boys/images/6/60/Homelander_S2.jpg/revision/latest?cb=20200808192351"},
    {quote: "Life isn’t actually a PR strategy. You can say what you think.", author: "Klara Risinger", img: "https://imgix.ranker.com/user_node_img/50115/1002285633/original/1002285633-photo-u1?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "If it comes to that, I’ll neutralize her.", author: "William Butcher", img: "https://imgix.ranker.com/user_node_img/50098/1001941889/original/billy-butcher-photo-u2?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "Who gives a shit if Vought burns to the fucking ground.", author: "Homelander", img: "https://static.wikia.nocookie.net/amazons-the-boys/images/6/60/Homelander_S2.jpg/revision/latest?cb=20200808192351"},
    {quote: "Aw, you can’t do your magic little hand thingy anymore? How come?", author: "Klara Risinger", img: "https://imgix.ranker.com/user_node_img/50115/1002285633/original/1002285633-photo-u1?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "Fuck Fresca!", author: "Kevin Moskowitz", img: "https://imgix.ranker.com/user_node_img/50098/1001941905/original/the-deep-photo-u2?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "I like your friends. Especially Hughie. He's good for you.", author: "Rebecca Saunders Butcher", img: "https://static.wikia.nocookie.net/amazons-the-boys/images/b/b7/Becca_Butcher.png/revision/latest/scale-to-width-down/310?cb=20201003022124"},
    {quote: "You can't have a cunt like me around that kid. I can't pass my shit on to him.", author: "William Butcher", img: "https://imgix.ranker.com/user_node_img/50098/1001941889/original/billy-butcher-photo-u2?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "It doesn't matter what we do. Nothing ever changes. Nothing changes or gets better, and I'm tired of it.", author: "Maggie Shaw", img: "https://imgix.ranker.com/user_node_img/50098/1001941902/original/-queen-maeve-photo-u2?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "If Billy Butcher can do the right thing, then there's gotta be some kind of higher power.", author: "Annie January", img: "https://imgix.ranker.com/user_node_img/50098/1001946199/original/behind-the-scenes-photo-u1?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "You didn't get the chance to say goodbye to Lenny?! You're the reason he's dead.", author: "William Butcher", img: "https://imgix.ranker.com/user_node_img/50098/1001941889/original/billy-butcher-photo-u2?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "Look, this isn't healthy. You can't watch porn while the sun's out.", author: "Hugh Campbell Jr.", img: "https://imgix.ranker.com/user_node_img/50098/1001941897/original/hughie-campbell-photo-u2?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "Hey! Tell Butcher about the thick penis around your neck!", author: "Serge", img: "https://imgix.ranker.com/user_node_img/50098/1001941895/original/-frenchie-photo-u2?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "Never go into shark infested waters without chum.", author: "William Butcher", img: "https://imgix.ranker.com/user_node_img/50098/1001941889/original/billy-butcher-photo-u2?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "So. When you see it on your uncle's Facebook page, then you know it's working!", author: "Klara Risinger", img: "https://imgix.ranker.com/user_node_img/50115/1002285633/original/1002285633-photo-u1?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "I know this is Dawn of the Seven, but it's sunset on A-Train.", author: "Reggie Franklin", img: "https://imgix.ranker.com/user_node_img/50098/1001941483/original/a-train-photo-u1?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "Ohhh. Oh. Huh. Pffft. So, what? They're all starving, but one of them's got a fucking a cell phone?", author: "Homelander", img: "https://static.wikia.nocookie.net/amazons-the-boys/images/6/60/Homelander_S2.jpg/revision/latest?cb=20200808192351"},
    {quote: "What good does grieving all alone ever do?", author: "Serge", img: "https://imgix.ranker.com/user_node_img/50098/1001941895/original/-frenchie-photo-u2?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "I think your sister is very special, and she loves you very much.", author: "Serge", img: "https://imgix.ranker.com/user_node_img/50098/1001941895/original/-frenchie-photo-u2?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "Can I tell you a secret? Sometimes, my eyes light up when I... you know.", author: "Annie January", img: "https://imgix.ranker.com/user_node_img/50098/1001946199/original/behind-the-scenes-photo-u1?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "I'm a fighter, I'm going to fight, yeah... I'm going to take that son of a bitch's head clean off.", author: "Annie January", img: "https://imgix.ranker.com/user_node_img/50098/1001946199/original/behind-the-scenes-photo-u1?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "It doesn't bother you that I could whip your ass in bowling? And in everything? And bench-press you?", author: "Annie January", img: "https://imgix.ranker.com/user_node_img/50098/1001946199/original/behind-the-scenes-photo-u1?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "I don't know if they really want you to be a hero.", author: "Annie January", img: "https://imgix.ranker.com/user_node_img/50098/1001946199/original/behind-the-scenes-photo-u1?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "I mean, I don't remember but my Mom said when I was born, I almost blinded the doctor. So, I had powers from the start.", author: "Annie January", img: "https://imgix.ranker.com/user_node_img/50098/1001946199/original/behind-the-scenes-photo-u1?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "You know there is this beach in the Bahamas where the sand is pink, like cotton-candy pink.", author: "Annie January", img: "https://imgix.ranker.com/user_node_img/50098/1001946199/original/behind-the-scenes-photo-u1?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "I don't know, I just know that, for me, New York has been such a shit show. Except for you. Somehow, In the middle of it all you found me.", author: "Annie January", img: "https://imgix.ranker.com/user_node_img/50098/1001946199/original/behind-the-scenes-photo-u1?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "You have to explain Hughie. You have to make this make sense. Just you and me. You owe me that much.", author: "Annie January", img: "https://imgix.ranker.com/user_node_img/50098/1001946199/original/behind-the-scenes-photo-u1?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "You made me think I was chosen by God.", author: "Annie January", img: "https://imgix.ranker.com/user_node_img/50098/1001946199/original/behind-the-scenes-photo-u1?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "This was your dream, I never got a chance to choose my own dream.", author: "Annie January", img: "https://imgix.ranker.com/user_node_img/50098/1001946199/original/behind-the-scenes-photo-u1?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "The thing is... I don't care.", author: "Annie January", img: "https://imgix.ranker.com/user_node_img/50098/1001946199/original/behind-the-scenes-photo-u1?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "Leave me alone, I'm not in the mood.", author: "Annie January", img: "https://imgix.ranker.com/user_node_img/50098/1001946199/original/behind-the-scenes-photo-u1?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "Turn around and walk away, A-Train", author: "Annie January", img: "https://imgix.ranker.com/user_node_img/50098/1001946199/original/behind-the-scenes-photo-u1?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "We're all alone. That's the truth.", author: "Annie January", img: "https://imgix.ranker.com/user_node_img/50098/1001946199/original/behind-the-scenes-photo-u1?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "Oh, gosh, moms. The gift that keeps on giving. Forever.", author: "Annie January", img: "https://imgix.ranker.com/user_node_img/50098/1001946199/original/behind-the-scenes-photo-u1?fit=crop&fm=pjpg&q=60&w=650&dpr=2"},
    {quote: "If you jump ship and let the assholes steer, then you're part of the problem.", author: "Annie January", img: "https://imgix.ranker.com/user_node_img/50098/1001946199/original/behind-the-scenes-photo-u1?fit=crop&fm=pjpg&q=60&w=650&dpr=2"}
];
