module.exports.Soundtracks = {
    the_flash: {
        title1: "https://open.spotify.com/album/0xiJwfDcZRQ77bsbjS9TF5",
        title2: "https://open.spotify.com/album/2EE7W74Rk1LDHzbYC9js2Z",
        title3: "https://open.spotify.com/album/0DCUAyJVmG1fNxkBaZqFLt",
        title4: "https://open.spotify.com/album/12WS02J0JBAVeEGj6aJ7R8",
    },
    arrow: {
        title1: "https://open.spotify.com/album/0Hsit07149488kiRI1UiaJ",
        title2: "https://open.spotify.com/album/234N1BIHMSxaKSVAM0JrOC",
        title3: "https://open.spotify.com/album/2SYmYystitleloAQkkr2TEncT",
        title4: "https://open.spotify.com/album/1IA3XNL6kv5zOpFG18M1au",
        title5: "https://open.spotify.com/album/7ivC8XKulyl3akjhiRtJjA",
        title6: "https://open.spotify.com/album/2sT1ks3i5yn0ZAGGvZQv92",
    },
    supergirl: {
        title1: "https://open.spotify.com/album/0jSqj8Tr0BrQIdqV4DZ9jD",
        title2: "https://open.spotify.com/album/7x4PDyJb3FJoYkRnF2hu2K",
        title3: "https://open.spotify.com/album/6zXns0k78HUh5UlNprKhvf",
    },
    legends_of_tomorrow: {
        title1: "https://open.spotify.com/album/0ceTcs3rDUEiyzshxjJFdB",
        title2: "https://open.spotify.com/album/4r6t4EyqVZskLi0jD9yOhU",
        title3: "https://open.spotify.com/album/0FPZ6xZBcwsupOaxKULGAF",
    },
    crossovers: {
        crossover_1: "https://open.spotify.com/album/7vs9fu0ORNPmV2opBjLu5z",
        crossover_2: "https://open.spotify.com/album/1jFljSQGFqtKkFNURoEOeI",
    }
}

module.exports.Quotes = [
    'Category:Alexandra_Danvers_(Arrow:_Earth-38)/Quotes',
    'Category:titlera_Kadtitlera_(Arrow)/Quotes',
    'Category:Francisco_Ramon_(Arrow)/Quotes',
    'Category:Emiko_Queen_(Arrow)/Quotes',
    'Category:Floyd_Lawton_(Arrow)/Quotes',
    'Category:John_Diggle_(Arrow)/Quotes',
    'Category:Carrie_Cutter_(Arrow)/Quotes',
    'Category:Jefferson_Jackson_(Arrow)/Quotes',
    'Category:Ricardo_Diaz_(Arrow)/Quotes',
    'Category:Maseo_Yamashiro_(Arrow)/Quotes',
    'Category:Rene_Ramirez_(Arrow)/Quotes',
    'Category:Benjamin_Turner_(Arrow)/Quotes',
    'Category:Felicity_Smoak_(Arrow)/Quotes',
    'Category:Barry_Allen_(Arrow)/Quotes',
    'Category:Harrison_Wells_(Arrow:_Earth-19)/Quotes',
    'Category:Evelyn_Sharp_(Arrow)/Quotes',
    'Category:Amanda_Waller_(Arrow)/Quotes',
    'Category:Helena_Bertinelli_(Arrow)/Quotes',
    'Category:Tobias_Church_(Arrow)/Quotes',
    'Category:Simon_Morrison_(Arrow)/Quotes',
    'Category:Damien_Darhk_(Arrow)/Quotes',
    'Category:Roy_Harper_(Arrow)/Quotes',
    'Category:Samandra_Watson_(Arrow)/Quotes',
    'Category:Kara_Zor-El_(Arrow:_Earth-38)/Quotes',
    'Category:Henry_Allen_(Arrow)/Quotes',
    'Category:Nathaniel_Heywood_(Arrow)/Quotes',
    'Category:Nora_Thompson_(Arrow)/Quotes',
    'Category:Catherine_Grant_(Arrow:_Earth-38)/Quotes',
    'Category:Jesse_Wells_(Arrow:_Earth-2)/Quotes',
    'Category:George_Lucas_(Arrow)/Quotes',
    'Category:Mia_Smoak_(Arrow)/Quotes',
    'Category:Zari_Tomaz_(Arrow)/Quotes',
    'Category:Winslow_Schott,_Jr._(Arrow:_Earth-X)/Quotes',
    'Category:Robert_Queen_(Arrow)/Quotes',
    'Category:Kal-El_(Arrow:_Earth-38)/Quotes',
    'Category:Leonard_Snart_(Arrow)/Quotes',
    'Category:Raymond_Palmer_(Arrow)/Quotes',
    'Category:John_Constantine_(Arrow)/Quotes',
    'Category:Dinah_Laurel_Lance_(Arrow:_Earth-2)/Quotes',
    'Category:Martin_Stein_(Arrow)/Quotes',
    'Category:Barry_Allen_(Arrow:_Earth-2)/Quotes',
    'Category:Rip_Hunter_(Arrow)/Quotes',
    'Category:Anatoli_Knyazev_(Arrow)/Quotes',
    'Category:Mallus_(Arrow)/Quotes',
    'Category:Hartley_Rathaway_(Arrow)/Quotes',
    'Category:Leslie_Jocoy_(Arrow)/Quotes',
    'Category:Harrison_Wells_(Arrow:_Earth-2)/Quotes',
    'Category:Malcolm_Merlyn_(Arrow)/Quotes',
    'Category:Nora_West-Allen_(Arrow)/Quotes',
    'Category:Dinah_Lance_(Arrow)/Quotes',
    'Category:J%27onn_J%27onzz_(Arrow:_Earth-38)/Quotes',
    'Category:Leonard_Snart_(Arrow:_Earth-X)/Quotes',
    'Category:Jay_Garrick_(Arrow:_Earth-3)/Quotes',
    'Category:Amaya_Jiwe_(Arrow)/Quotes',
    'Category:John_Diggle,_Jr._(Arrow:_Star_City_2046)/Quotes',
    'Category:Julian_Albert_Desmond_(Arrow)/Quotes',
    'Category:Eobard_Thawne_(Arrow)/Quotes',
    'Category:Hunter_Zolomon_(Arrow:_Earth-2)/Quotes',
    'Category:Mick_Rory_(Arrow)/Quotes',
    'Category:James_Olsen_(Arrow:_Earth-38)/Quotes',
    'Category:Samantha_Clayton_(Arrow)/Quotes',
    'Category:James_Jesse_(Arrow)/Quotes',
    'Category:Donna_Smoak_(Arrow)/Quotes',
    'Category:Music_Meister_(Arrow:_Earth-38)/Quotes',
    'Category:Nyssa_al_Ghul_(Arrow)/Quotes',
    'Category:Grodd_(Arrow)/Quotes',
    'Category:Edward_Clariss_(Arrow)/Quotes',
    'Category:Ralph_Dibny_(Arrow)/Quotes',
    'Category:Clyde_Mardon_(Arrow)/Quotes',
    'Category:Brainiac_8_(Arrow:_Earth-38)/Quotes',
    'Category:Desmond_(Arrow)/Quotes',
    'Category:Sara_Lance_(Arrow)/Quotes',
    'Category:Harleen_Quinzel_(Arrow)/Quotes',
    'Category:Thomas_Merlyn_(Arrow:_Earth-X)/Quotes',
    'Category:Katherine_Kane_(Arrow)/Quotes',
    'Category:Dinah_Laurel_Lance_(Arrow)/Quotes',
    'Category:Izzy_Bowin_(Arrow)/Quotes',
    'Category:Edward_Thawne_(Arrow)/Quotes',
    'Category:Clifford_DeVoe_(Arrow)/Quotes',
    'Category:John_Deegan_(Arrow)/Quotes',
    'Category:Iris_West_(Arrow)/Quotes',
    'Category:Eliza_Danvers_(Arrow:_Earth-38)/Quotes',
    'Category:Kelex_(Arrow:_Earth-38)/Quotes',
    'Category:Savitar_(Arrow)/Quotes',
    'Category:Caitlin_Snow_(Arrow)/Quotes'
]

module.exports.Speedsters = [
    {
        speedster: "The Flash (Barry Allen)",
        lightningColorsElectrokinesis: "Yellow (Speed Force) 🡒 Orange (+Speed)",
        universe: "Earth-1",
        actoractress: "Grant Gustin",
        firstAppearance: "Arrow 2x08 \"The Scientist\"",
        firstAppearanceAsSpeedster: "Flash 1x01 \"Pilot\"",
        image: "https://vignette.wikia.nocookie.net/arrow/images/9/90/The_Flash.png/revision/latest/scale-to-width-down/350?cb=20190327234611"
    },
    {
        speedster: "The Reverse Flash (Eobard Thawne)",
        lightningColorsElectrokinesis: "Red (Negative Speed Force)",
        universe: "Earth-1",
        actoractress: "Tom Cavanagh / Matt Letscher",
        firstAppearance: "Flash 1x01 \"Pilot\"",
        firstAppearanceAsSpeedster: "Flash 1x06 \"The Flash Is Born\"",
        image: "https://vignette.wikia.nocookie.net/arrow/images/b/b3/Reverse-Flash.png/revision/latest/scale-to-width-down/350?cb=20190626233852"
    },
    {
        speedster: "Zoom / Black Flash (Hunter Zolomon)",
        lightningColorsElectrokinesis: "Yellow (Speed Force) 🡒 Blue (V6) 🡒 Red (Transformed)",
        universe: "Earth-2",
        actoractress: "Teddy Sears / Tony Todd",
        firstAppearance: "Flash 2x01 \"The Man Who Saved Central City\"",
        firstAppearanceAsSpeedster: "Flash 2x01 \"The Man Who Saved Central City\"",
        image: "https://vignette.wikia.nocookie.net/arrow/images/9/96/Zoom.png/revision/latest/scale-to-width-down/350?cb=20170728183556"
    },
    {
        speedster: "Savitar (Barry Allen - Time Remnant)",
        lightningColorsElectrokinesis: "Yellow (Speed Force) 🡒 White (Suit)",
        universe: "Earth-1",
        actoractress: "Grant Gustin / Tobin Bell",
        firstAppearance: "The Flash 3x02 \"Paradox\" ",
        firstAppearanceAsSpeedster: "The Flash 3x02 \"Paradox\"",
        image: "https://www.monstersandcritics.com/wp-content/uploads/2017/04/flashSavitar-e1493137477278.png"
    },
    {
        speedster: "Godspeed (August Heart)",
        lightningColorsElectrokinesis: "White (Tachyons) / Blue Sparks (V9)",
        universe: "Earth-1",
        actoractress: "Kindall Charters / B.D. Wong",
        firstAppearance: "The Flash 5x18 \"Godspeed\"",
        firstAppearanceAsSpeedster: "The Flash 5x18 \"Godspeed\"",
        image: "https://vignette.wikia.nocookie.net/arrow/images/e/e3/Godspeed.png/revision/latest/scale-to-width-down/350?cb=20190418050140"
    },
    {
        speedster: "The Red Death (Bruce Wayne)",
        lightningColorsElectrokinesis: "Red (Speed Force)",
        universe: "Earth-52",
        actoractress: "Unknown",
        firstAppearance: "Unknown",
        firstAppearanceAsSpeedster: "Unknown",
        image: "https://fsmedia.imgix.net/28/97/95/4b/ec75/42a3/9517/b1682c837835/batman-the-red-death-1-cover-by-jason-ftitleok-and-dean-white.jpeg#image"
    },
    {
        speedster: "Accelerated Man",
        lightningColorsElectrokinesis: "Purple (Speed Force)",
        universe: "Earth-19",
        actoractress: "Sean Poague",
        firstAppearance: "Flash 3x14 \"Attack on Central City\"",
        firstAppearanceAsSpeedster: "Flash 3x14 \"Attack on Central City\"",
        image: "https://vignette.wikia.nocookie.net/arrow/images/9/9a/Accelerated_Man.png/revision/latest/scale-to-width-down/350?cb=20170301042811"
    },
    {
        speedster: "Jesse Quick (Jesse Chambers Wells)",
        lightningColorsElectrokinesis: "Yellow (Speed Force)",
        universe: "Earth-2",
        actoractress: "Violett Beane",
        firstAppearance: "Flash 2x05 \"The Darkness and the Light\"",
        firstAppearanceAsSpeedster: "Flash 3x03 \"Magenta\"",
        image: "https://vignette.wikia.nocookie.net/arrow/images/9/93/Jesse_Quick.png/revision/latest/scale-to-width-down/350?cb=20180310230252"
    },
    {
        speedster: "The Flash (Jay Garrick)",
        lightningColorsElectrokinesis: "Orange (Speed Force)",
        universe: "Earth-3",
        actoractress: "John Wesley Shipp",
        firstAppearance: "Flash 2x13 \"Welcome to Earth-2\"",
        firstAppearanceAsSpeedster: "Flash 2x23 \"The Race of His Life\"",
        image: "https://vignette.wikia.nocookie.net/arrow/images/1/10/The_Flash_%28Jay_Garrick%29.png/revision/latest/scale-to-width-down/350?cb=20170107101535"
    },
    {
        speedster: "The Rival (Edward Clariss)",
        lightningColorsElectrokinesis: "Red (Speed Force)",
        universe: "Earth-1",
        actoractress: "Todd Lasance",
        firstAppearance: "Flash 3x01 \"Flashpoint\"",
        firstAppearanceAsSpeedster: "Flash 3x01 \"Flashpoint\"",
        image: "https://vignette.wikia.nocookie.net/arrow/images/e/ee/The_Rival.png/revision/latest/scale-to-width-down/350?cb=20161019195539"
    },
    {
        speedster: "Trajectory (Eliza Harmon)",
        lightningColorsElectrokinesis: "Yellow (V9) 🡒 Blue (Overdose V9)",
        universe: "Earth-1",
        actoractress: "Allison Paige",
        firstAppearance: "Flash 2x16 \"Trajectory\"",
        firstAppearanceAsSpeedster: "Flash 2x16 \"Trajectory\"",
        image: "https://vignette.wikia.nocookie.net/arrow/images/8/87/Trajectory.png/revision/latest/scale-to-width-down/350?cb=20160323032622"
    },
    {
        speedster: "Music Meister",
        lightningColorsElectrokinesis: "Orange (Speed Force) [Stolen]",
        universe: "Unknown",
        actoractress: "Darren Criss",
        firstAppearance: "Supergirl 2x16 \"Star-Crossed\"",
        firstAppearanceAsSpeedster: "Flash 3x17 \"Duet\"",
        image: "https://vignette.wikia.nocookie.net/arrow/images/c/c6/Music_Meister.png/revision/latest/scale-to-width-down/350?cb=20170321032713"
    },
    {
        speedster: "The Flash (Oliver Queen)",
        lightningColorsElectrokinesis: "Orange (Speed Force) [Rewritten Reality]",
        universe: "Earth-1",
        actoractress: "Stephen Amell",
        firstAppearance: "Arrow 1x01 \"Pilot\"",
        firstAppearanceAsSpeedster: "Flash 5x09 \"Elseworlds, Part 1\"",
        image: "https://imgix.bustle.com/uploads/image/2018/12/3/0a436c2f-571f-4de7-88fe-4d38728a0718-ar709b_0753b.jpg?w=970\u0026h=546\u0026fit=crop\u0026crop=faces\u0026auto=format\u0026q=70"
    },
    {
        speedster: "A.M.A.Z.O.",
        lightningColorsElectrokinesis: "Orange (Speed Force) [Copied]",
        universe: "Earth-1",
        actoractress: "CGI",
        firstAppearance: "Flash 5x09 \"Elseworlds, Part 1\"",
        firstAppearanceAsSpeedster: "Flash 5x09 \"Elseworlds, Part 1\"",
        image: "https://vignette.wikia.nocookie.net/arrow/images/d/da/A.M.A.Z.O..png/revision/latest/scale-to-width-down/350?cb=20190114052414"
    },
    {
        speedster: "The Flash (Barry Allen)",
        lightningColorsElectrokinesis: "Yellow (Speed Force)",
        universe: "Earth-90",
        actoractress: "John Wesley Shipp",
        firstAppearance: "Flash 5x09 \"Elseworlds, Part 1\"",
        firstAppearanceAsSpeedster: "Flash 5x09 \"Elseworlds, Part 1\"",
        image: "https://vignette.wikia.nocookie.net/arrow/images/2/26/The_Flash_%28Earth-90%29.png/revision/latest/scale-to-width-down/350?cb=20190316075355"
    },
    {
        speedster: "Kid Flash (Wally West)",
        lightningColorsElectrokinesis: "Yellow (Speed Force)",
        universe: "Earth-1",
        actoractress: "Keiynan Lonsdale",
        firstAppearance: "Flash 2x09 \"Running to Stand Still\"",
        firstAppearanceAsSpeedster: "Flash 3x01 \"Flashpoint\"",
        image: "https://vignette.wikia.nocookie.net/arrow/images/c/cf/Kid_Flash.png/revision/latest/scale-to-width-down/350?cb=20170526014156"
    },
    {
        speedster: "The Flash (Iris West-Allen)",
        lightningColorsElectrokinesis: "Purple (Speed Force) [Melting Point]",
        universe: "Earth-1",
        actoractress: "Candice Patton",
        firstAppearance: "Flash 1x01 \"Pilot\"",
        firstAppearanceAsSpeedster: "Flash 4x16 \"Run Iris Run\"",
        image: "https://akns-images.eonline.com/eol_images/Entire_Site/2018122/rs_634x1024-180222103245-634-candice-patton-flash-cw.png?fit=inside|900:auto\u0026output-quality=90"
    },
    {
        speedster: "XS (Nora West-Allen)",
        lightningColorsElectrokinesis: "Purple \u0026 Yellow (Speed Force) / Purple \u0026 Red (Negative Speed Force)",
        universe: "Earth-1",
        actoractress: "Jessica Parker Kennedy",
        firstAppearance: "Supergirl 3x08 \"Crisis on Earth-X, Part 1\"",
        firstAppearanceAsSpeedster: "Flash 4x20 \"Therefore She Is\"",
        image: "https://vignette.wikia.nocookie.net/arrow/images/6/67/XS.png/revision/latest/scale-to-width-down/350?cb=20181102205101"
    }
]

module.exports.titleilities = {
    speedsters: {
        title1: "",
        ability1: "",
        title2: "",
        ability2: "",
        title3: "",
        ability3: "",
        title4: "",
        ability4: "",
    },
    vibers: {
        title1: "",
        title2: "",
        title3: "",
        title4: "",
        title5: "",
        title6: "",
    },
    kryptonians: {
        title1: "https://open.spotify.com/album/0jSqj8Tr0BrQIdqV4DZ9jD",
        title2: "https://open.spotify.com/album/7x4PDyJb3FJoYkRnF2hu2K",
        title3: "https://open.spotify.com/album/6zXns0k78HUh5UlNprKhvf",
    }
}