module.exports.Soundtracks = {
    flash: {
        season1: "https://open.spotify.com/album/0xiJwfDcZRQ77bsbjS9TF5",
        season2: "https://open.spotify.com/album/2EE7W74Rk1LDHzbYC9js2Z",
        season3: "https://open.spotify.com/album/0DCUAyJVmG1fNxkBaZqFLt",
        season4: "https://open.spotify.com/album/12WS02J0JBAVeEGj6aJ7R8",
    },
    arrow: {
        season1: "https://open.spotify.com/album/0Hsit07149488kiRI1UiaJ",
        season2: "https://open.spotify.com/album/234N1BIHMSxaKSVAM0JrOC",
        season3: "https://open.spotify.com/album/2SYmYysseasonloAQkkr2TEncT",
        season4: "https://open.spotify.com/album/1IA3XNL6kv5zOpFG18M1au",
        season5: "https://open.spotify.com/album/7ivC8XKulyl3akjhiRtJjA",
        season6: "https://open.spotify.com/album/2sT1ks3i5yn0ZAGGvZQv92",
    },
    supergirl: {
        season1: "https://open.spotify.com/album/0jSqj8Tr0BrQIdqV4DZ9jD",
        season2: "https://open.spotify.com/album/7x4PDyJb3FJoYkRnF2hu2K",
        season3: "https://open.spotify.com/album/6zXns0k78HUh5UlNprKhvf",
    },
    lot: {
        season1: "https://open.spotify.com/album/0ceTcs3rDUEiyzshxjJFdB",
        season2: "https://open.spotify.com/album/4r6t4EyqVZskLi0jD9yOhU",
        season3: "https://open.spotify.com/album/0FPZ6xZBcwsupOaxKULGAF",
    },
    crossovers: {
        crossover1: "https://open.spotify.com/album/4AtHQFEn8Qrp9aSSt0ehob", //Flash vs. Arrow
        crossover2: "https://open.spotify.com/album/7vs9fu0ORNPmV2opBjLu5z", //Duet
        crossover3: "https://open.spotify.com/album/1jFljSQGFqtKkFNURoEOeI", //COEX
    }
}

module.exports.Quotes = {
    sections: [{
        content: [
            {"title": "Category:Alexandra_Danvers_(Arrowverse:_Earth-38)/Quotes"},
            {"title": "Category:Abra_Kadabra_(Arrowverse)/Quotes"},
            {"title": "Category:Francisco_Ramon_(Arrowverse)/Quotes"},
            {"title": "Category:Emiko_Queen_(Arrowverse)/Quotes"},
            {"title": "Category:Floyd_Lawton_(Arrowverse)/Quotes"},
            {"title": "Category:John_Diggle_(Arrowverse)/Quotes" },
            {"title": "Category:Carrie_Cutter_(Arrowverse)/Quotes"},
            {"title": "Category:Jefferson_Jackson_(Arrowverse)/Quotes"},
            {"title": "Category:Ricardo_Diaz_(Arrowverse)/Quotes"},
            {"title": "Category:Maseo_Yamashiro_(Arrowverse)/Quotes"},
            {"title": "Category:Rene_Ramirez_(Arrowverse)/Quotes"},
            {"title": "Category:Benjamin_Turner_(Arrowverse)/Quotes"},
            {"title": "Category:Felicity_Smoak_(Arrowverse)/Quotes"},
            {"title": "Category:Barry_Allen_(Arrowverse)/Quotes"},
            {"title": "Category:Harrison_Wells_(Arrowverse:_Earth-19)/Quotes"},
            {"title": "Category:Evelyn_Sharp_(Arrowverse)/Quotes"},
            {"title": "Category:Amanda_Waller_(Arrowverse)/Quotes"},
            {"title": "Category:Helena_Bertinelli_(Arrowverse)/Quotes"},
            {"title": "Category:Tobias_Church_(Arrowverse)/Quotes"},
            {"title": "Category:Simon_Morrison_(Arrowverse)/Quotes"},
            {"title": "Category:Damien_Darhk_(Arrowverse)/Quotes"},
            {"title": "Category:Roy_Harper_(Arrowverse)/Quotes"},
            {"title": "Category:Samandra_Watson_(Arrowverse)/Quotes"},
            {"title": "Category:Kara_Zor-El_(Arrowverse:_Earth-38)/Quotes"},
            {"title": "Category:Henry_Allen_(Arrowverse)/Quotes"},
            {"title": "Category:Nathaniel_Heywood_(Arrowverse)/Quotes"},
            {"title": "Category:Nora_Thompson_(Arrowverse)/Quotes"},
            {"title": "Category:Catherine_Grant_(Arrowverse:_Earth-38)/Quotes"},
            {"title": "Category:Jesse_Wells_(Arrowverse:_Earth-2)/Quotes"},
            {"title": "Category:George_Lucas_(Arrowverse)/Quotes"},
            {"title": "Category:Mia_Smoak_(Arrowverse)/Quotes"},
            {"title": "Category:Zari_Tomaz_(Arrowverse)/Quotes"},
            {"title": "Category:Winslow_Schott,_Jr._(Arrowverse:_Earth-X)/Quotes"},
            {"title": "Category:Robert_Queen_(Arrowverse)/Quotes"},
            {"title": "Category:Kal-El_(Arrowverse:_Earth-38)/Quotes"},
            {"title": "Category:Leonard_Snart_(Arrowverse)/Quotes"},
            {"title": "Category:Raymond_Palmer_(Arrowverse)/Quotes"},
            {"title": "Category:John_Constantine_(Arrowverse)/Quotes"},
            {"title": "Category:Dinah_Laurel_Lance_(Arrowverse:_Earth-2)/Quotes"},
            {"title": "Category:Martin_Stein_(Arrowverse)/Quotes"},
            {"title": "Category:Barry_Allen_(Arrowverse:_Earth-2)/Quotes"},
            {"title": "Category:Rip_Hunter_(Arrowverse)/Quotes"},
            {"title": "Category:Anatoli_Knyazev_(Arrowverse)/Quotes"},
            {"title": "Category:Mallus_(Arrowverse)/Quotes"},
            {"title": "Category:Hartley_Rathaway_(Arrowverse)/Quotes"},
            {"title": "Category:Leslie_Jocoy_(Arrowverse)/Quotes"},
            {"title": "Category:Harrison_Wells_(Arrowverse:_Earth-2)/Quotes"},
            {"title": "Category:Malcolm_Merlyn_(Arrowverse)/Quotes"},
            {"title": "Category:Nora_West-Allen_(Arrowverse)/Quotes"},
            {"title": "Category:Dinah_Lance_(Arrowverse)/Quotes"},
            {"title": "Category:J%27onn_J%27onzz_(Arrowverse:_Earth-38)/Quotes"},
            {"title": "Category:Leonard_Snart_(Arrowverse:_Earth-X)/Quotes"},
            {"title": "Category:Jay_Garrick_(Arrowverse:_Earth-3)/Quotes"},
            {"title": "Category:Amaya_Jiwe_(Arrowverse)/Quotes"},
            {"title": "Category:John_Diggle,_Jr._(Arrowverse:_Star_City_2046)/Quotes"},
            {"title": "Category:Julian_Albert_Desmond_(Arrowverse)/Quotes"},
            {"title": "Category:Eobard_Thawne_(Arrowverse)/Quotes"},
            {"title": "Category:Hunter_Zolomon_(Arrowverse:_Earth-2)/Quotes"},
            {"title": "Category:Mick_Rory_(Arrowverse)/Quotes"},
            {"title": "Category:James_Olsen_(Arrowverse:_Earth-38)/Quotes"},
            {"title": "Category:Samantha_Clayton_(Arrowverse)/Quotes"},
            {"title": "Category:James_Jesse_(Arrowverse)/Quotes"},
            {"title": "Category:Donna_Smoak_(Arrowverse)/Quotes"},
            {"title": "Category:Music_Meister_(Arrowverse:_Earth-38)/Quotes"},
            {"title": "Category:Nyssa_al_Ghul_(Arrowverse)/Quotes"},
            {"title": "Category:Grodd_(Arrowverse)/Quotes"},
            {"title": "Category:Edward_Clariss_(Arrowverse)/Quotes"},
            {"title": "Category:Ralph_Dibny_(Arrowverse)/Quotes"},
            {"title": "Category:Clyde_Mardon_(Arrowverse)/Quotes"},
            {"title": "Category:Brainiac_8_(Arrowverse:_Earth-38)/Quotes"},
            {"title": "Category:Desmond_(Arrowverse)/Quotes"},
            {"title": "Category:Sara_Lance_(Arrowverse)/Quotes"},
            {"title": "Category:Harleen_Quinzel_(Arrowverse)/Quotes"},
            {"title": "Category:Thomas_Merlyn_(Arrowverse:_Earth-X)/Quotes"},
            {"title": "Category:Katherine_Kane_(Arrowverse)/Quotes"},
            {"title": "Category:Dinah_Laurel_Lance_(Arrowverse)/Quotes"},
            {"title": "Category:Izzy_Bowin_(Arrowverse)/Quotes"},
            {"title": "Category:Edward_Thawne_(Arrowverse)/Quotes"},
            {"title": "Category:Clifford_DeVoe_(Arrowverse)/Quotes"},
            {"title": "Category:John_Deegan_(Arrowverse)/Quotes"},
            {"title": "Category:Iris_West_(Arrowverse)/Quotes"},
            {"title": "Category:Eliza_Danvers_(Arrowverse:_Earth-38)/Quotes"},
            {"title": "Category:Kelex_(Arrowverse:_Earth-38)/Quotes"},
            {"title": "Category:Savitar_(Arrowverse)/Quotes"},
            {"title": "Category:Caitlin_Snow_(Arrowverse)/Quotes"}
        ]}
    ]
}

module.exports.Speedsters = [
    {
        speedster: "The Flash (Barry Allen)",
        lightningColorsElectrokinesis: "Yellow (Speed Force) 🡒 Orange (+Speed)",
        universe: "Earth-1",
        actoractress: "Grant Gustin",
        firstAppearanceAsSpeedster: "The Flash 1x01 \"Pilot\""
    },
    {
        speedster: "The Reverse-Flash (Eobard Thawne)",
        lightningColorsElectrokinesis: "Red (Negative Speed Force)",
        universe: "Earth-1",
        actoractress: "Tom Cavanagh / Matt Letscher",
        firstAppearanceAsSpeedster: "The Flash 1x06 \"The Flash Is Born\""
    },
    {
        speedster: "Zoom / Black Flash (Hunter Zolomon)",
        lightningColorsElectrokinesis: "Yellow (Speed Force) 🡒 Blue (V6) 🡒 Red (Transformed)",
        universe: "Earth-2",
        actoractress: "Teddy Sears / Tony Todd",
        firstAppearanceAsSpeedster: "The Flash 2x01 \"The Man Who Saved Central City\" "
    },
    {
        speedster: "Savitar (Barry Allen - Time Remnant)",
        lightningColorsElectrokinesis: "Yellow (Speed Force) 🡒 White (Suit)",
        universe: "Earth-1",
        actoractress: "Grant Gustin / Tobin Bell",
        firstAppearanceAsSpeedster: "The Flash 3x02 \"Paradox\" "
    },
    {
        speedster: "Godspeed (August Heart)",
        lightningColorsElectrokinesis: "White (Speed Force) [Tachyons] / Blue Sparks (V9)",
        universe: "Earth-1",
        actoractress: "Kindall Charters / B.D. Wong",
        firstAppearanceAsSpeedster: "The Flash 5x18 \"Godspeed\""
    },
    {
        speedster: "G4 (Unnamed Godspeed)",
        lightningColorsElectrokinesis: "White (Speed Force) [Clone]",
        universe: "Earth-1",
        actoractress: "Ryan Handley",
        firstAppearanceAsSpeedster: "The Flash 6x01 \"Into The Void\""
    },
    {
        speedster: "Accelerated Man",
        lightningColorsElectrokinesis: "Purple (Speed Force)",
        universe: "Earth-19",
        actoractress: "Sean Poague",
        firstAppearanceAsSpeedster: "The Flash 3x14 \"Attack on Central City\""
    },
    {
        speedster: "Jesse Quick (Jesse Chambers Wells)",
        lightningColorsElectrokinesis: "Yellow (Speed Force)",
        universe: "Earth-2",
        actoractress: "Violett Beane",
        firstAppearanceAsSpeedster: "The Flash 3x03 \"Magenta\" "
    },
    {
        speedster: "The Flash (Jay Garrick)",
        lightningColorsElectrokinesis: "Orange (Speed Force)",
        universe: "Earth-3",
        actoractress: "John Wesley Shipp",
        firstAppearanceAsSpeedster: "The Flash 2x23 \"The Race of His Life\" "
    },
    {
        speedster: "The Rival (Edward Clariss)",
        lightningColorsElectrokinesis: "Red (Speed Force) [Philosopher's Stone]",
        universe: "Earth-1",
        actoractress: "Todd Lasance",
        firstAppearanceAsSpeedster: "The Flash 3x01 \"Flashpoint\" "
    },
    {
        speedster: "Trajectory (Eliza Harmon)",
        lightningColorsElectrokinesis: "Yellow (V9) 🡒 Blue (Overdose V9)",
        universe: "Earth-1",
        actoractress: "Allison Paige",
        firstAppearanceAsSpeedster: "The Flash 2x16 \"Trajectory\" "
    },
    {
        speedster: "Music Meister",
        lightningColorsElectrokinesis: "Orange (Speed Force) [Stolen]",
        universe: "Unknown",
        actoractress: "Darren Criss",
        firstAppearanceAsSpeedster: "The Flash 3x17 \"Duet\" "
    },
    {
        speedster: "The Flash (Oliver Queen)",
        lightningColorsElectrokinesis: "Orange (Speed Force) [Rewritten Reality]",
        universe: "Earth-1",
        actoractress: "Stephen Amell",
        firstAppearanceAsSpeedster: "The Flash 5x09 \"Elseworlds, Part 1\" "
    },
    {
        speedster: "A.M.A.Z.O.",
        lightningColorsElectrokinesis: "Orange (Speed Force) [Copied]",
        universe: "Earth-1",
        actoractress: "CGI",
        firstAppearanceAsSpeedster: "The Flash 5x09 \"Elseworlds, Part 1\" "
    },
    {
        speedster: "The Flash (Barry Allen)",
        lightningColorsElectrokinesis: "Yellow (Speed Force)",
        universe: "Earth-90",
        actoractress: "John Wesley Shipp",
        firstAppearanceAsSpeedster: "The Flash 5x09 \"Elseworlds, Part 1\" "
    },
    {
        speedster: "Kid Flash (Wally West)",
        lightningColorsElectrokinesis: "Yellow (Speed Force) [Philosopher's Stone]",
        universe: "Earth-1",
        actoractress: "Keiynan Lonsdale",
        firstAppearanceAsSpeedster: "The Flash 3x01 \"Flashpoint\" "
    },
    {
        speedster: "The Flash (Iris West-Allen)",
        lightningColorsElectrokinesis: "Purple (Speed Force) [Melting Point]",
        universe: "Earth-1",
        actoractress: "Candice Patton",
        firstAppearanceAsSpeedster: "The Flash 4x16 \"Run Iris Run\""
    },
    {
        speedster: "XS (Nora West-Allen)",
        lightningColorsElectrokinesis: "Purple & Yellow (Speed Force) / Purple & Red (Negative Speed Force)",
        universe: "Earth-1",
        actoractress: "Jessica Parker Kennedy",
        firstAppearanceAsSpeedster: "The Flash 4x20 \"Therefore She Is\""
    },
    {
        speedster: "The Flash (Gorilla Grodd)",
        lightningColorsElectrokinesis: "Orange (Speed Force) [Mindscape Merge]",
        universe: "Earth-Prime",
        actoractress: "David Sobolov / Grant Gustin",
        firstAppearanceAsSpeedster: "The Flash 6x13 \"Grodd Friended Me\""
    }
]

module.exports.Abilities = {
    speedsters: {
        title1: "Speed Force connection/Meta-human physiology",
        ability1: "A Speedster's powers come from a connection to the Speed Force, this alters and supercharges their DNA, cells, and neurotransmitters, augmenting their physiology.",
        title2: "Accelerated healing factor",
        ability2: "Without treatment, most damage heals in hours if not minutes with no lingering signs. Even normally permanent damage, like paraplegia, is completely repaired in days.",
        title3: "Bodily vibration",
        ability3: "Speedsters can vibrate their body for various effects.",
        title4: "Seismokinesis",
        ability4: "By vibrating at varying frequencies and with different levels of force, speedsters can create small tremors to induce extreme amounts of jolt on any target they touch.",
        title5: "Intangibility",
        ability5: "By vibrating their molecules at the frequency of air, speedsters can physically pass through solid matter.",
        title6: "Invisibility",
        ability6: "Speedsters can vibrate their body so fast that they can no longer be perceived by the human eye.",
        title7: "Electrokinesis",
        ability7: "Speedsters can produce electricity in various colors, their Speed Force energy, from their body. It is commonly seen when running to boost their already immense speed to far higher levels.",
        title8: "Speed Force sharing (Unique to Barry Allen)",
        ability8: "Barry can expand his Speed Force aura to protect others he carries while moving at super speed.",
        title9: "Superhuman strength",
        ability9: "Speedsters physical strength has been heightened beyond that of normal human capacities.",
        title10: "Superhuman durability",
        ability10: "Speedsters possess inhuman resilience, most commonly seen from being unaffected by momentum build-up. They can take attacks and exertion, even survive impacts that would easily kill normal humans.",
        title11: "Superhuman mental process",
        ability11: "A Speedsters powers also make their system and thought processing able to take in and retain information just as fast and efficiently. Even while using their raw speed, they can clearly think, react to events, and perform actions long before normal humans can perceive them.",
        title12: "Superhuman perceptions",
        ability12: "A Speedsters senses are also enhanced. This allows them to perceive the world as if it is nearly frozen. They can see and hear normally, even while moving at speeds faster than sound, where this would normally be impossible.",
        title13: "Superhuman speed",
        ability13: "Speedsters can move at such vast speeds, indeterminable to the naked eye.",
        title14: "Superhuman agility",
        ability14: "Speedsters possess flawless coordination, equilibrium and dexterity, they can change direction with immediate sharp turns without sliding or losing balance and instantly stop running on the spot.",
        title15: "Superhuman reflexes",
        ability15: "A Speedsters reaction time is augmented to superhuman levels, allowing them to react to danger and events far faster than normal humans.",
        title16: "Superhuman momentum",
        ability16: "Speedsters can generate great amounts of physical force through kinetic energy, simulating superhuman strength, even in a stationary position.",
        title17: "Aerokinesis",
        ability17: "Speedsters can use their speed to generate air flows on various levels and for various effects.",
        title18: "Time travel",
        ability18: "The kinetic energy buildup from a speedsters speed can allow them to breach the space-time continuum, allowing them to physically enter the Speed Force and travel through time.",
        title19: "Time reversal (Unique to Nora West-Allen)",
        ability19: "Nora is able to reverse time around her while running, remaining completely unaffected.",
        title20: "Inter-dimensional travel",
        ability20: "Speedsters can move fast enough to break open portals between dimensions, allowing them to travel to different universes.",
        title21: "Speed mirages",
        ability21: "Speedsters can generate illusions of themselves to make it appear as if they were in many places at once, when in reality they are simply bouncing back and forth too fast for the human mind to perceive the difference.",
        title22: "Temporal regression (Unique to Barry Allen)",
        ability22: "With his ability to shift through time, Barry can also reverse the flow effects while running at a certain speed, while he remains completely unaffected.",
        title23: "Temporal dilution (Unique to Barry Allen & Nora West-Allen)",
        ability23: "By generating enough energy, Barry and Nora can move so fast that time essentially slows down relative to them, to a complete standstill.",
        title24: "Time remnant construct",
        ability24: "Speedsters are able to \"create\" a time remnant by traveling back to moments before their current-self time travels, hailing from a future that no longer exists. This allows them to be two places at once.",
        title25: "Temporal awareness",
        ability25: "Speedsters are able to subconsciously detect when other speedsters enter the Speed Force to time travel.",
        title26: "Speed Force awareness",
        ability26: "With concentration, speedsters can sense the Speed Force in another speedster's system.",
        title27: "Superhuman stamina",
        ability27: "Speedsters can handle the stresses of extreme racing without noticeable distress, letting them function much longer than normal humans unhindered. Their enhanced stamina is due to their augmented physiology, which builds up little to no lactic acid or fatigue toxins."
    },
    vibers: {
        title1: "Meta-human physiology",
        ability1: "Vibers possess altered DNA and physiology to access dimensional energy.",
        title2: "Dimensional energy manipulation",
        ability2: "Vibers have a psychic link to the natural energies of reality, allowing them to connect with various vibrations of the multiverse and manipulate them for various effects.",
        title3: "Dimensional awareness",
        ability3: "Known as \"vibing\", vibers can perceive various events throughout time and space, letting them see into the past and future as well as parallel dimensions, even into the very Speed Force itself.",
        title4: "Inter-dimensional travel",
        ability4: "With their natural connection to the multiverse, vibers can open portals to other dimensions. Being a noticeably more advanced ability, they are shown to need focus and a proper awareness of their intended target.",
        title5: "Vibrational blasts",
        ability5: "Vibers are able to generate powerful blue or red concussive blasts of vibrations from their hands capable of propelling full-grown humans through the air.",
        title6: "Mental connection",
        ability6: "Vibers are connected by their powers and are able to observe each other if they're skilled enough."
    },
    kryptonians: {
        title1: "Kryptonian physiology",
        ability1: "A kryptonians capabilities are no greater than those of a human. However, once charged by the energy spectrum of a yellow sun, they become able to perform various inhuman feats.",
        title2: "Solar energy absorption",
        ability2: "Kryptonian powers are dependent on the energy spectrum from a yellow sun, their body is able to constantly and passively absorb such energy while exposed to it, essentially keeping their reserves fully charged near-constantly.",
        title3: "Accelerated healing factor",
        ability3: "Kryptonian metabolism is tremendously enhanced by solar energy, allowing accelerated healing abilities and burning calories at a superhuman rate, making them practically immune to becoming fat or obese.",
        title4: "Contaminant immunity",
        ability4: "Kryptonians have an immunity to all forms of disease and contaminants on Earth.",
        title5: "Resurrection",
        ability5: "After they die, kryptonians are able to self-resurrect by absorbing solar energy from flora in their vicinity.",
        title6: "Flight",
        ability6: "Kryptonians are able to manipulate their own gravitational field to generate thrust and propel themselves through the air, often at hyper-sonic speeds, much faster than they can travel by foot.",
        title7: "Sleep flight",
        ability7: "Kryptonians have the ability to float in the air while they sleep.",
        title8: "Levitation",
        ability8: "Kryptonians can levitate using their flight abilities.",
        title9: "Heat vision",
        ability9: "By concentrating every solar energy reserve they have in their body, kryptonians can emit blue or red energy beams of variable intensity and temperature from their eyes.",
        title10: "Invulnerability",
        ability10: "Kryptonians are essentially invulnerable to all Earthly weapons, with bullets simply ricocheting whenever they come into contact with their skin.",
        title11: "Extreme heat resistance",
        ability11: "Kryptonians feel no pain when exposed to extreme heat.",
        title12: "Self-sustenance",
        ability12: "Due to the effects of a yellow sun, a kryptonians physical needs are greatly reduced.",
        title13: "Atmospheric adaption",
        ability13: "While kryptonians do require oxygen, their physicality and exposure to a yellow sun allows them to survive while inhaling more harsh forms of it such as the thin, highly CO2-concentrated, atmosphere of Mars.",
        title14: "Reverse photosynthesis",
        ability14: "Kryptonians are capable of draining solar energy from plants even without a direct source of light.",
        title15: "Super vision",
        ability15: "Kryptonians are able to see very far distances, presumably at peak human or low superhuman levels. They are even able to see clearly in the dark.",
        title16: "X-ray vision",
        ability16: "Kryptonians possess the ability to see through objects, except for lead.",
        title17: "Super breath",
        ability17: "Kryptonians are able to exhale powerful gusts of air from their mouth which are similar to force winds. They can also cause the temperature of their breath to drop, therefore able to freeze nearly anything.",
        title18: "Super hearing",
        ability18: "Kryptonians have super-sensitive ears that can perfectly pick up sounds from miles away and even through structures.",
        title19: "Super speed",
        ability19: "Kryptonians possess the ability to move at hyper-sonic speeds, both through flight and on foot.",
        title20: "Accelerated perception",
        ability20: "While using their super speed, Kryptonians see everything much slower, allowing them to move with precision and accuracy within very fast moments.",
        title21: "Super reflexes",
        ability21: "A kryptonians reflexes are so fast, that they can respond to attacks within seconds.",
        title22: "Time deceleration",
        ability22: "When a kryptonian and a speedster (or another kryptonian) run/fly around the Earth in opposite directions, they are able to slow the Earth's rotation, along with time itself",
        title23: "Super strength",
        ability23: "A kryptonians strength is enhanced under a yellow sun, enough to easily kill a normal human if they were to attack them directly.",
        title24: "Thunderclap",
        ability24: "When kryptonians use their super strength to clap their hands together, it creates a powerful shock-wave that throws enemies back.",
        title25: "Super jumping/leaping",
        ability25: "Kryptonians are able to jump several feet off the ground and leap several stories in a single bound without having to fly.",
        title26: "Super stamina",
        ability26: "Kryptonians can run, fight or fly for long periods of time, without getting tired.",
        title27: "Extended longevity",
        ability27: "A Kryptonians life span is considerably longer than a humans and they likewise age much slower.",
        title28: "Telepathy immunity",
        ability28: "Kryptonians are immune to most forms of telepathic powers.",
        title29: "Power bestowal via electricity",
        ability29: "If a kryptonian is holding a person while electrocuted by lightning, their kryptonian physiology allows them to affect the person, giving the person strange abilites.",
    }
}

module.exports.API = {
    API: {
        status: "Gideon API online and functional!"
    }
}

module.exports.Invite = "https://discord.gg/h9SEQaU";
